wso2/andes

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distrupter/ConcurrentBatchProcessor.java
modules/orbit/andes/pom.xml

as part of build stabiliazation.

Changes up to Jan 14 - 2015

---

modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java

Refer commit message. 
Jira : https://wso2.org/jira/browse/MB-939

Fix for jira MB-939

---

modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/AMQPUtils.java
modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/QpidAMQPBridge.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesBinding.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageFlusher.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/CQLBasedAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorBasedAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/AMQPLocalSubscription.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java

Fixes for following Jiras
- https://wso2.org/jira/browse/MB-941
- https://wso2.org/jira/browse/MB-942

Durable subscription path improvements and fix for queue delete issue

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextInformationManager.java

Fixed issue of queue not getting deleted from UI when deleted.
JIRA - https://wso2.org/jira/browse/MB-945

Fixed queue deletion through UI.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTLocalSubscription.java
modules/andes-core/broker/src/test/java/org/wso2/andes/server/queue/AMQQueueMBeanTest.java
modules/andes-core/broker/src/test/java/org/wso2/andes/server/store/MessageStoreTest.java
modules/andes-core/common.xml
modules/andes-core/module.xml
modules/gentools/build.xml

- Upgrade to Java 6
- Removed deprecated method usages
Jira: https://wso2.org/jira/browse/MB-947

Upgrade ant build version to Java 6

---

modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java

When queues and topics have the same name and there are durable subscriptions
messages sent to the topic get received by the queue subscription as well.
This was fixed by filtering the durable subscriptions in clusterQueueSubscriptionMap
appropriately.

Fix for queues and topics with same name

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConnection.java

improve logging message when login failure to database.
jira - https://wso2.org/jira/browse/MB-944

[MB-944] improve logging message when login failure to database.

---

modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/messaging/spi/impl/ProtocolProcessor.java

Remove mqtt subscription when subscriber disconnects without unsubscribing.

Remove mqtt subscription when subscriber disconnects.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConnection.java

fix issue in RDBMSConnection class. added StringUtils.isBlank(dataSource.getUsername()) to verify if username exist in dataSource.

[MB-944] fix issue in RDBMSConnection class

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java

- link https://wso2.org/jira/browse/MB-950

MB-950 issue fixed.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java

- link https://wso2.org/jira/browse/MB-954

MB-954 issue fixed.

---

modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/messaging/spi/impl/subscriptions/SubscriptionsStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesMessageMetadata.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscription.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageFlusher.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTLocalSubscription.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTUtils.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/AMQPLocalSubscription.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/BasicSubscription.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java

Resolve MQTT/AMQP delivery paths.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/qpid/ConfigStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/qmf/QMFService.java

[MB-958] Fixing the problems with the build of andes with oracle jdk 1.8

---

modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/QpidAMQPBridge.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTUtils.java

Fix for timestamp issue in non-durable topic path.
jira - https://wso2.org/jira/browse/MB-960

[MB-960] fix timestamp issue in topic messages.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/delivery/DeliveryEventHandler.java

- link https://wso2.org/jira/browse/MB-962

MB-962 issue fixed.

---

modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/messaging/spi/impl/ProtocolProcessor.java
modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/messaging/spi/impl/SimpleMessaging.java
modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/messaging/spi/impl/UserAuthenticator.java
modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/server/Server.java
modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/AndesConfigurationManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/MQTTUserAuthenticationScheme.java
modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/TopicMatchingSelection.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/delivery/DeliveryEventHandler.java

Relavent Jira ID : https://wso2.org/jira/browse/MB-722

[MB-722] Authenticating users against Carbon user store

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageFlusher.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/OnflightMessageTracker.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/OrphanedSlotHandler.java

- link https://wso2.org/jira/browse/MB-953
- link https://wso2.org/jira/browse/MB-955

MB-953 and MB-955 issue fixed.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/AMQPUtils.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/OrphanedSlotHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java

- link https://wso2.org/jira/browse/MB-951

MB-951 issue fixed.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/AMQChannel.java

Adding subscription if user is authorized.

Adding subscription if user authorized

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java

fix for ora-00911 invalid character issue in oracle
jira - https://wso2.org/jira/browse/MB-981

[MB-981] fix for ORA-00911: invalid character issue in oracle

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java

Fix class cast exception and avoid subscription close exception when server is shutting down.

Fix server close exception issues.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java

fix for error occurred when durable subscription removed from mb node.
jira - https://wso2.org/jira/browse/MB-983

[MB-983] fix for ORA-00911: invalid character issue when remove durable subscription

---

modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java

Removed shortform 'if' conditions in Subscription Store

Removed shortform 'if' conditions in Subscription Store

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/ClusterManager.java

Added logging for node initialization.

Added logging for node initialization.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextInformationManager.java

1. Added comments on exchanges and bindings.

Added comments on AndesContextInformationManage.java

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/ClusterManager.java

The UI was showing the wrong coordinator.
JIRA - https://wso2.org/jira/browse/MB-988

[MB-988] Added fix to show correct coordinator on UI.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/delivery/ContentCacheCreator.java

Code refactored in allowing empty messages to be received from the message store.

Code refactored in allowing empty messages to be received from the message store.

---

modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQConnection.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQSession.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/protocol/AMQProtocolHandler.java

JIRA https://wso2.org/jira/browse/MB-999

Fix issue with MB failover with flow control enabled

---

modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/ClusterSubscriptionProcessor.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java

Fix updating the subscription store subscription object when disconnecting and validate active subscribers.

Fix updating the subscriptions.

---

modules/andes-core/pom.xml
modules/orbit/andes-client/pom.xml
modules/orbit/andes/pom.xml
pom.xml

- move dependency version to property
- format pom.xml

pom.xml changes

---

modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/server/Server.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/Broker.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/Main.java

Fix for jira : https://wso2.org/jira/browse/MB-771
Support to disable/enable amqp or mqtt transport listeners. 
*The configuration properties had been added in a previous PR to broker.xml

Fix mb 771

---

modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/server/Server.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/Broker.java

Fixing compiler issue specific to java 1.6 related to PR : 105
Issue explanation : http://stackoverflow.com/questions/5666027/why-does-the-compiler-state-no-unique-maximal-instance-exists

Fix generics type detection issue specific to java 1.6

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/ClusterCoordinationHandler.java

- https://wso2.org/jira/browse/MB-1020

MB-1020 issue fixed.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotCoordinator.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotCoordinatorCluster.java
modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/MBThriftClient.java
modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/SlotManagementServiceImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/slot/gen/SlotManagementService.java
modules/andes-core/broker/src/main/resources/slot.thrift

Fix with reference to : https://wso2.org/jira/browse/MB-143?focusedCommentId=98155&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-98155

Update slot thrift def for queue purge

---

modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/InboundEventManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageFlusher.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/OnflightMessageTracker.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/DisruptorBasedInboundEventManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/InboundKernelOpsEvent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeletionScheduler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/MBThriftClient.java

- Completely revamp shutting down sequence in andes dependency

MB-1021 issue fixed

---

modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/messaging/spi/impl/ProtocolProcessor.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesMessageMetadata.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/OnflightMessageTracker.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/RetainedContent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/TopicParserUtil.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/InboundEventContainer.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/InboundSubscriptionEvent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/MessagePreProcessor.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/MessageWriter.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTopicManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/connectors/DistributedStoreConnector.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/utils/MQTTUtils.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/CQLBasedMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorBasedMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/h2/H2MemMessageStoreImpl.java

This will add retain feature to mb.
jira - https://wso2.org/jira/browse/MB-867

[MB-867] mqtt retain feature

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/MessagePreProcessor.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/connectors/DistributedStoreConnector.java

- Fix to send publisher acknowledgements when a message is ignored.
(When there are no subscribers for the topic message is dropped, but
we need to acknowledge the publisher in this scenario)

Send publisher acknowledge even when dropping topic messages

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/Broker.java

Used "InetAddress.getByName(bindAddressFromBrokerOptions);" instead of "InetAddress.getByAddress(parseIP(bindAddr));" .

[MB-875] Fix to provide a hostname in broker.xml

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/queue/DLCQueueUtils.java

JIRA - https://wso2.org/jira/browse/MB-691

[MB-691] Modifed isDLC check method.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTSubscriber.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTopicManager.java

JIRA - https://wso2.org/jira/browse/MB-1029

Implement code for avoid adding QOS 0 MQTT messages to clean session

---

modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/AMQPMessage.java
modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/QpidAndesBridge.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesMessage.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/MessagePreProcessor.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTMessage.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/connectors/DistributedStoreConnector.java

Jira - https://wso2.org/jira/browse/MB-1036

Remove protocol specific implementation from kernel

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/InboundSubscriptionEvent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/MessagePreProcessor.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/MessageWriter.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/CQLBasedMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/CQLConstants.java

This PR will add cassandra CQL implementation for mqtt retain and fix minor issues in retain feature.

Fix mqtt retain related issues

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/MessageWriter.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingMessageStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/CQLBasedMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorBasedMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java

This PR will remove retained message list and replaced it with a hash map.

[MB-867] Improvements to mqtt retain topics

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java

This PR will close unclosed connection and fix some of task naming issues.

Close sql connection in getAllRetainedTopics and fix task naming issues in RDBMS impl

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorBasedAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorBasedMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorConnection.java

Keyspace name change to get by config in hector based message/context stores

INFO log added to inform user in slot mapping at server startup

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/AMQBrokerManagerMBean.java

JIRA - https://wso2.org/jira/browse/MB-1056

[MB-1056] Fix deleting queue through UI.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DurableStoreConnection.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingMessageStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingStoreManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/CQLConnection.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/CassandraDataAccessException.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorBasedAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorBasedMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorConnection.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorDataAccessHelper.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorUtils.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConnection.java

In addition to MB-1043 this PR includes some enhancements for hector based message store.
Jira: https://wso2.org/jira/browse/MB-1043

MB-1043 Implement the ability to detect Cassandra availability for Hector based message stores

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotMessageCounter.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/ClusterManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/HazelcastAgent.java

When a node with publishers crash subscribers on remaining node couldn't get some messages. The messages are in DB, but not delivered to subscribers untill more messages are published to the same queue.
This is the fix for that issue.
Jira: https://wso2.org/jira/browse/MB-1066

Fix for messages not delivered after a node crash

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/queue/SimpleAMQQueue.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/security/SecurityManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/security/access/Operation.java

- public jira url : https://wso2.org/jira/browse/MB-1065

MB-1065 issue fixed.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/RetainedContent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/TopicParserUtil.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/InboundSubscriptionEvent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/CQLBasedMessageStoreImpl.java

This PR will include code review changes and code improvements.

Code review changes and code improvements.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/SubscriptionManagementInformationMBean.java

JIRA - https://wso2.org/jira/browse/MB-1084

[MB-1084] - Modified subscription ID on the UI.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/Broker.java

This will fix issue in following jira.
https://wso2.org/jira/browse/MB-1077

[MB-1077] fix error when adding  multiple IP addresses for same host name

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotMessageCounter.java

Removed method is already called.

Build fix in SlotMessageCounter. 

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/ConnectionException.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/OrphanedSlotHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/Slot.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotCoordinationConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeletionScheduler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorker.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorkerManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerStandalone.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotMessageCounter.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotUtils.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/custom/serializer/HashMapStringTreeSetWrapperSerializer.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/custom/serializer/TreeSetSlotWrapperSerializer.java

- Indentation issues fixed
- Spelling mistakes fixed
- Java 7 build related IntellijIdea warnings resolved

Code refactoring related to slot package

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeleteSafeZoneCalc.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotUtils.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/AMQPLocalSubscription.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/QueueSenderAdapter.java

Some improvements to slot management logic.

Improvements to Slot management logic

---

modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/QueueBrowserDeliveryWorker.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerStandalone.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/CQLBasedMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorBasedMessageStoreImpl.java
modules/andes-core/management/common/src/main/java/org/wso2/andes/management/common/mbeans/QueueManagementInformation.java

queue browse tombstone reading issue fixed in cassadra
please note that queue browse cause major response
delay when message store is cassandra depend on tombstone count
and this would cause to browser timeout depending on configuration.

queue browse pagination support added

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java

Fix issues in delete functionality in MQTT retain feature.
JIRA - https://wso2.org/jira/browse/MB-1125

Fix issues in delete MQTT retain entries

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java

Adresses the jira https://wso2.org/jira/browse/MB-1132
Since a foreign key relationship was added between the two tables, message metadata and content, it was unnecessary to delete message content explicitly.

Method, deleteMessages modified to only delete message metadata

---

modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/AndesConfigurationManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/qpid/ServerConfiguration.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/security/auth/manager/PrincipalDatabaseAuthenticationManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/AndesDataException.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/AndesDataIntegrityViolationException.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSStoreUtils.java
modules/andes-core/pom.xml
modules/andes-core/systests/src/main/java/org/wso2/andes/server/logging/DerbyMessageStoreLoggingTest.java
modules/orbit/andes/pom.xml
pom.xml

Jira: https://wso2.org/jira/browse/MB-1130
This change will upgrade the commons-configuration also v 1.10 (latest at the time of change)

[MB-1130] Fix error based flow control for mssql drivers.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/Slot.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeleteSafeZoneCalc.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/SlotAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/HazelcastAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/rdbms/RDBMSAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingAndesContextStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/CQLBasedAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorBasedAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/h2/H2MemAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/SlotManagementServiceImpl.java
modules/andes-core/pom.xml
modules/orbit/andes-client/pom.xml

This code will replace hazelcast maps to RDBMS information saving

[WIP]Implement a mechanism to save information in RDBMS

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java

Merge issue fixed

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java

JIRA - https://wso2.org/jira/browse/MB-734

[MB-734] - Added default mime type for message browsing on UI.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextInformationManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundQueueEvent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/metrics/MetricsConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingMessageStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/CQLBasedAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/CQLBasedMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorBasedMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java

Addresses the jira https://wso2.org/jira/browse/MB-1079

Message deletion in DLC when purging a queue

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/OnflightMessageTracker.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/OrphanedMessageHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/subscription/SubscriptionImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/AMQPLocalSubscription.java

jira : https://wso2.org/jira/browse/MB-1148

[MB-1148] Fixes for observable performance degradation 

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/StateEventHandler.java

Fix issue in not sending mqtt pub ack properly.

Remove wrongly used pub ack handler

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java

Jira - https://wso2.org/jira/browse/MB-1156

Slot return fix

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeletionExecutor.java

SlotDeletionExecutor modified to delete given slot until coordinator return
true. Previous logic wrote to try once and if coordinator return false add
it back to queue. This was caused long delay to delete slot.

SlotDeletionExecutor modification

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/MessageWriter.java

The messages in the retain map was not retried in case of an error. Is it the correct behavior?

Add missing error handling task to Exception catch block

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DeliveryEventHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/MessagePreProcessor.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/StateEventHandler.java

JIRA - https://wso2.org/jira/browse/MB-1135

Non-reporting metrics fixed

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageFlusher.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/OnflightMessageTracker.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/AckHandler.java

This will move the call to release slot and tracking data after
the call to delete metadata from store

Remove slot and tracking data after metadata is removed from store

---

modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/server/Server.java
modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/AndesConfigurationManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/qpid/ServerConfiguration.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/ClusterManager.java

Added bind addresses per each transport. This change will enable AMQP and MQTT use separate bind addresses.
jira - https://wso2.org/jira/browse/MB-1159

[MB-1159] bind address per transport

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/OnflightMessageTracker.java

Jira: https://wso2.org/jira/browse/MB-1034

[MB-1034] Reverting a minor change

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContext.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundKernelOpsEvent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotCoordinatorCluster.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/ClusterAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/ClusterManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/CoordinatorInformation.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/HazelcastClusterAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/AndesMembershipListener.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/HazelcastAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/SlotManagementServiceImpl.java

Please note that this has a dependency with https://github.com/wso2/carbon-business-messaging/pull/99.

Implement new coordinator selection algorithm

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DisruptorBasedFlusher.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundEventManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/MessagePreProcessor.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingMessageStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/tools/utils/MessageTracer.java

JIRA - https://wso2.org/jira/browse/MB-1152

New message tracing events updated

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
modules/andes-core/broker/src/main/java/org/wso2/andes/metrics/MetricsConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/queue/IncomingMessage.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingMessageStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/CQLBasedMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorBasedMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/h2/H2MemMessageStoreImpl.java
modules/andes-core/management/common/src/main/java/org/wso2/andes/management/common/mbeans/QueueManagementInformation.java

This addresses the jira https://wso2.org/jira/browse/MB-1144
Please merge https://github.com/wso2/carbon-business-messaging/pull/92 along with this or else the tests will fail.

Implemented store level operations for the updated DLC

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageFlusher.java

- Non durable topic delivery path changes revert back to original state to avoid message loss by dropping messages to subscriber who doesn't has room to accept message to deliver.

Non durable topic delivery path changes

---

modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQSession.java

This addresses the problem regarding 'andesWaitTimeOut' being not working properly as mentioned in 
jira https://wso2.org/jira/browse/MB-1141
The problem was due to the delay in the time that is taken to update the 'deliveredTimeStamp' of messages

Fixed andesAckWaitTimeOut issue

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java

Addresses jira https://wso2.org/jira/browse/MB-1163
The problem was in the ordering of entering values for parameters in the prepared statement.
Also, a place where a variable was not initialized was corrected

Fixed arithmetic exception in RDBMS slot management

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/ClusterAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/ClusterManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/HazelcastClusterAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/HazelcastAgent.java

JIRA - https://wso2.org/jira/browse/MB-1090

Added methods to set and get node id from broker.xml

---

modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesChannel.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DisruptorCachedContent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/LocalSubscription.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/ConcurrentContentReadTaskBatchProcessor.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/ContentCacheCreator.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DeliveryEventData.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTLocalSubscription.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/AMQPLocalSubscription.java

This is to fix fetching the same message content from message store.

Message content caching improvement in delivery disruptor

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageFlusher.java

Fix for error occurred while sending messages to subscribers from buffer java.util.NoSuchElementException
jira - https://wso2.org/jira/browse/MB-1167

[MB-1167] Fix NoSuchElement exception in messageFlusher

---

modules/andes-core/client/src/main/java/org/wso2/andes/jndi/PropertiesFileInitialContextFactory.java

This addressed the jira https://wso2.org/jira/browse/MB-1161

Add secure vault support to the andes client

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/ClusterManager.java

This is the fix for the jira https://wso2.org/jira/browse/MB-1118
The issue occurred due to the long time taken by the method to check the operational status of the db to return when the database was heavily loaded. It was fixed by caching the result of the last operational check and simply returning the cached value when needed to view.

[WIP] Thread dead issue fixed

---

modules/andes-core/client/src/main/java/org/wso2/andes/jndi/PropertiesFileInitialContextFactory.java

Revert "Add secure vault support to the andes client"

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesRecoveryTask.java

JIRA - https://wso2.org/jira/browse/MB-1147

Implement StoreHealthListener to AndesRecoveryTask

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/ClusterAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/HazelcastClusterAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/HazelcastAgent.java

JIRA - https://wso2.org/jira/browse/MB-1101

Throw exception when duplicate node ids detected on sever startup

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeleteSafeZoneCalc.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
modules/andes-core/broker/src/main/java/org/wso2/andes/metrics/MetricsConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/ClusterManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/rdbms/RDBMSAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingAndesContextStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java

This PR contains review changes for several merged pull requests.

Code review changes

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/SubscriptionManagementInformationMBean.java
modules/andes-core/management/common/src/main/java/org/wso2/andes/management/common/mbeans/QueueManagementInformation.java

Addresses the jira https://wso2.org/jira/browse/MB-1171
Please merge https://github.com/wso2/carbon-business-messaging/pull/112 along with this or else the tests will fail

Durable topic subscription message browsing added

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesChannel.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/connectors/PersistenceStoreConnector.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/AMQChannel.java

JIRA - https://wso2.org/jira/browse/MB-1122

Added identifer and destination name to flow control message

---

modules/andes-core/client/src/main/java/org/wso2/andes/jndi/PropertiesFileInitialContextFactory.java

Reverts wso2/andes#253
This PR need to be tested before merged again.

Revert "[MB-1161]Add secure vault support to the andes client"

---

modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/messaging/spi/impl/ProtocolProcessor.java

As a temporary fix we skip the tenant domain check for super tenant
users when publishing and subscribing

Fix for hierarchical topic test case failure

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingMessageStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/CQLBasedMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorBasedMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java

Removed some unused methods and changed some code lines which seemed out of the convention.

Refeactored code in RDBMSMessageStoreImpl

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java

addresses the jira https://wso2.org/jira/browse/MB-1179
Please merge https://github.com/wso2/product-mb/pull/154 along with this or else the tests will fail

Set default auto commit status to false

---

modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/MBThriftServer.java

JIRA - https://wso2.org/jira/browse/MB-1174

[MB-1174] Prevent node from starting if using 0.0.0.0 as thrift server host

---

pom.xml

Addresses the jira https://wso2.org/jira/browse/MB-1182
Upgraded the carbon kernel version from 4.4.0 to 4.4.1
Please merge https://github.com/wso2/carbon-business-messaging/pull/119 and https://github.com/wso2/product-mb/pull/159 along with this

Updated to kernel 4.4.1

---

modules/andes-core/client/src/main/java/org/wso2/andes/jndi/PropertiesFileInitialContextFactory.java

Revert "Revert "[MB-1161]Add secure vault support to the andes client""

---

modules/orbit/andes-client/pom.xml
pom.xml

Addresses the jira https://wso2.org/jira/browse/MB-1175. Added the dependencies required to have securevault support
Please merge https://github.com/wso2/andes/pull/253 and https://github.com/wso2/product-mb/pull/152 along with this to add enable securevault support

[WIP] Added Securevault dependency

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesRecoveryTask.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTMessage.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/connectors/PersistenceStoreConnector.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/AMQChannel.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/HazelcastClusterAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/SlotAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/HazelcastAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/rdbms/RDBMSAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/CQLBasedAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorBasedAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorBasedMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/MBThriftServer.java
modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/SlotManagementServiceImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/tools/utils/MessageTracer.java

This PR has code changes for previously merged PRs.

Review code changes

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java

Fix issues occured when removing non-durable subscriptions.
jira - https://wso2.org/jira/browse/MB-1172

[MB-1172] Fix issues in remove non durable subscriptions

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/ExtractResendAndRequeue.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/queue/DLCQueueUtils.java

Related JIRA https://wso2.org/jira/browse/MB-762

Fix for MB-762

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/SlotAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/HazelcastAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/rdbms/DatabaseSlotAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingAndesContextStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/CQLBasedAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorBasedAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java

JIRA - https://wso2.org/jira/browse/MB-1177

Reset slot tables when initializing cluster

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/cache/AndesMessageCache.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cache/DisabledMessageCache.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cache/GuavaBasedMessageCache.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java
modules/orbit/andes-client/pom.xml
modules/orbit/andes/pom.xml

The Jira: https://wso2.org/jira/browse/MB-1189
guava lib version is also upgraded with this PR.

[MB-1189] Ability to disable cache

---

modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/QpidAndesBridge.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesMessageMetadata.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlledQueueMessageDeliveryImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MaximumNumOfDeliveryRule.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageExpiredRule.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageFlusher.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagePurgeRule.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/NoLossBurstTopicMessageDeliveryImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/OnflightMessageTracker.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/SlowestSubscriberTopicMessageDeliveryImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DeliveryEventHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorker.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTLocalSubscription.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/queue/QueueEntry.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/queue/QueueEntryImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/AMQPLocalSubscription.java
modules/andes-core/broker/src/test/java/org/wso2/andes/server/exchange/AbstractHeadersExchangeTestBase.java
modules/andes-core/broker/src/test/java/org/wso2/andes/server/queue/MockQueueEntry.java

Set redelivery to message

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageData.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/OnflightMessageTracker.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DisruptorBasedFlusher.java

- Client acknowledgement issue reported in https://wso2.org/jira/browse/MB-1195 fixed.

MB-1195 fixed.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java

Fixed concurrent modification on reload subscriptions from DB. Also added necessary used locks.

Fixed concurrent modification on reload subscriptions from DB

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorker.java

- Concurrent modification exception reported in public jira - https://wso2.org/jira/browse/MB-1223 and it is fixed by changing Set to ConcurrentSkipListSet in messageBufferingTracker.

MB-1223 issue fixed.

---

modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/server/netty/NettyMQTTHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTMessageMetaData.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java

This issue was observed when the messages were published using two
producers, and consumed using two subscribers (QOS 0, clean
session false)
https://wso2.org/jira/browse/MB-1228

[MB-1228] Fix intermittent message loss in MQTT subscriber

---

modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/messaging/spi/impl/ProtocolProcessor.java

JIRA - https://wso2.org/jira/browse/MB-1183 ,  https://wso2.org/jira/browse/MB-1211

[MB-1183] [MB-1211] Added same client ID validation for MQTT

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/rdbms/DatabaseSlotAgent.java

Addresses the jira https://wso2.org/jira/browse/MB-1236

[MB-1236] Implemented store health aware database slot agent

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/HazelcastAgent.java
modules/andes-core/pom.xml
pom.xml

Addresses the jira https://wso2.org/jira/browse/MB-1237

[MB-1237] Modified cluster implementation to have hazelcast reliable topics

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/ClusterManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/HazelcastClusterAgent.java

JIRA - https://wso2.org/jira/browse/MB-1246

[MB-1246] Fixed durable sub failover when node ID is set in broker.xml

---

modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/messaging/spi/impl/ProtocolProcessor.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/ClusterManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/HazelcastClusterAgent.java

JIRA - https://wso2.org/jira/browse/MB-1246
JIRA - https://wso2.org/jira/browse/MB-1183 , https://wso2.org/jira/browse/MB-1211

[MB-1183] [MB-1211] Added same client ID validation for MQTT, [MB-1246] Fixed durable sub failover when node ID is set in broker.xml.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java

JIRA - https://wso2.org/jira/browse/MB-1253

[MB-1253] Replace " SELECT * " in RDBMS queries

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlledQueueMessageDeliveryImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java

Fix an issue with requeing durable topic sub messages and durable topic subscription disconnect.

Durable topic subscription close issue fix

---

modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/connectors/PersistenceStoreConnector.java

Fix wrong comments in sendRetainMessagesToSubscriber()

[MB-1259] Fix comment in sendRetainMessagesToSubscriber method

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DeliverableAndesMetadata.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/Slot.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorker.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/LocalSubscription.java

1. Message status dumping is fixed. There was an stack overflow error. 
2. Removed variable unAcknowledgedMsgCount as it is tracked by sending tracker.

Bug fixes in andes.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java

fixed issue of adding multiple subscription entries in DB for durable topic subscriptions.

Fix multiple durable topic subscription entries in DB

---

README.md
pom.xml

jira : https://wso2.org/jira/browse/MB-1250

[MB-1250] minor change relating to identity upgrade

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/Broker.java

https://wso2.org/jira/browse/MB-1309

[MB-1309] Add trustore configurations when creating the SSLContext in server

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotCreator.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java

This implements slot recovering task without a scheduled task.
https://wso2.org/jira/browse/MB-1260

[MB-1260] Use ConcurrentHashMaps for slot recovering datastructures

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingAndesContextStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/CQLBasedAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorBasedAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java

Addresses the jira https://wso2.org/jira/browse/MB-1277

[MB-1277] Deactivate durable subscriptions at startup of the first node

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundQueueEvent.java

Addresses the issue reported at https://wso2.org/jira/browse/MB-1131
Please merge https://github.com/wso2/carbon-business-messaging/pull/138 along with this

[MB-1131] Made the queue addition operation blocking

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DisruptorBasedFlusher.java

MB can hang if the tasks are continuously put in to outbound disruptor when it tries to shutdown. This should not happen normally. But in an error scenario this can make MB hang. Therefore added a timeout to avoid MB being hanged due to this.
https://wso2.org/jira/browse/MB-1287

[MB-1287] MB hanged when shutting down

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/queue/DLCQueueUtils.java

Addresses the issue reported at https://wso2.org/jira/browse/MB-1312.
The DLC subscription seemed to be not needed.

[MB-1312] Removed subscription for DLC

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java

Addresses https://wso2.org/jira/browse/MB-1346

[MB-1346] Refactored code in RDBMSConstants

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java

This PR will fix following jira.
https://wso2.org/jira/browse/MB-1342

[MB-1342] Unique constraint violation fix

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java

Fixing https://wso2.org/jira/browse/MB-1371

Fix Queue Browse When Message Delivery is Active.

---

modules/andes-core/broker/src/main/java/org/dna/mqtt/commons/Constants.java
modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/server/Server.java
modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/server/netty/NettyAcceptor.java
modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/qpid/ServerConfiguration.java

Fix for secure/non-secure port enable/disable from broker configurations. Some code refactoring also included.
https://wso2.org/jira/browse/MB-1338
https://wso2.org/jira/browse/MB-1339

[MB-1338][MB-1339] Fix port enable/disable issue and refactor code

---

modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java

Changes related to https://wso2.org/jira/browse/MB-1230
Related to broker.xml ; in AndesConfiguration and MessagingEngine

Changes related to JIRA MB-1230

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java

JIRA - https://wso2.org/jira/browse/MB-1374

[MB-1374] Queue mapping deletion from database bug gix

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextInformationManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/OrphanedMessageHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundKernelOpsEvent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundQueueEvent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/StateEventHandler.java

This class is not needed after removal of Cassandra data store
Jira: https://wso2.org/jira/browse/MB-1396

Remove message count flusher class

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/Slot.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotCoordinatorCluster.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeleteSafeZoneCalc.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotMessageCounter.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotState.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotUtils.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/SlotAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/HazelcastAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/rdbms/DatabaseSlotAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/BasicAckMethodHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingAndesContextStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQSession_0_8.java

- Replaces the Timer used in SlotMessageCounter with a ScheduledExecutorService
- Remove nodeInformedSlotDeletionSafeZones map from Slot Coordinator

Refactor slot timeout task

---

modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/AMQPUtils.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesMessagePart.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/ContentCacheCreator.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundQueueEvent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/metrics/MetricsConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingMessageStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java
modules/andes-core/broker/src/test/java/org/wso2/andes/kernel/disruptor/inbound/ContentChunkHandlerTest.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQSession.java
modules/andes-core/management/common/src/main/java/org/wso2/andes/management/common/mbeans/QueueManagementInformation.java

This PR adds code review changes and code improvements.

Review Changes

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotCreator.java
modules/andes-core/broker/src/main/java/org/wso2/andes/metrics/MetricsConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingMessageStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java

jira: https://wso2.org/jira/browse/MB-1359
we only need message IDs to re-create the slot maps. metadata is not needed.

[MB1359] Optmize Warm start time

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java

Reverts wso2/andes#377 due to cluster test failure. Failing test case is MultipleSubscriberMultiplePublisherTestCase.

Revert "[MB-1374] Queue mapping deletion from database bug gix"

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java

Addresses the issue reported at https://wso2.org/jira/browse/MB-1434

[MB-1434] Removed durable topic subscriptions from queue list

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java

Removed an incorrect error log.

Removed incorrect log

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/SubscriptionManagementInformationMBean.java

Fixing https://wso2.org/jira/browse/MB-1267

Fix topic subscriptions tenant wise filtering for UI

---

modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTopicManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/connectors/PersistenceStoreConnector.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/utils/MQTTUtils.java

Fix for - https://wso2.org/jira/browse/MB-1333

[MB-1333] When creating a topic mqtt, concatenate clientId with topic name for queueIdentifier

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java

fix for SQL integrity violation error when multiple durable shared
subscribers connecting to multiple MB nodes
JIRA: https://wso2.org/jira/browse/MB-1438

[MB-1438] Fix for multiple durable shared subscriber connection to a cluster

---

modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/AMQPUtils.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/BasicPublishMethodHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java

Fix for - https://wso2.org/jira/browse/MB-1431

Restrict publishing to AMQP topics with wildcards

---

modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/messaging/spi/impl/ProtocolProcessor.java
modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/proto/messages/SubAckMessage.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTAuthorizationSubject.java

For MQTT 3.1.1 clients will get return code 8 (forbidden subscription) from broker if it doesn't have privileges to subscribe to given topic. 
jira - https://wso2.org/jira/browse/MB-1409

[MB-1409] Send sub ack return code if refused to subscribe (for MQTT 3.1.1 spec)

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java

Public Jira : https://wso2.org/jira/browse/MB-1439

Fixed MB-1439

---

modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/messaging/spi/impl/ProtocolProcessor.java

Jira is : https://wso2.org/jira/browse/MB-1422
The retained flag is not set to true when client recieves a retained message

Fixing MB-1422, The retained flag is not set to true when client recieves a retained message

---

modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/AMQPUtils.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesMessagePart.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesUtils.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/rdbms/DatabaseSlotAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/queue/DLCQueueUtils.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java

Changes according to review comments

[WIP] Review changes

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/Slot.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorker.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java

Fixing : https://wso2.org/jira/browse/MB-1212

removed unnecessary logs and fix state violation on slot model.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/ClusterSubscriptionBitMapHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/ClusterSubscriptionHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/ClusterSubscriptionProcessor.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java

Tracked by https://wso2.org/jira/browse/MB-1466

Fixed MB-1466

---

modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQSession.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/BasicMessageProducer.java

Addresses the issue reported at https://wso2.org/jira/browse/MB-1433
Added queues and bindings when creating a publisher.

[MB-1433] Create queue when publishing

---

modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/QpidAndesBridge.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesAckData.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/AMQPLocalSubscription.java

Add fixes done to make NoAckSubscription work.
https://wso2.org/jira/browse/MB-1479

[MB-1479] [RabbitMQ] Error when subscribing/retrieving messages through a RabbitMQ client

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/SubscriptionManagementInformationMBean.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/ClusterSubscriptionBitMapHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/ClusterSubscriptionHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/ClusterSubscriptionProcessor.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java

This pull fixes https://wso2.org/jira/browse/MB-1446.
Retrieve wildcard subscriptions when browsed through UI.

Display durable wildcard subscription in the console

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/AMQChannel.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/ack/UnacknowledgedMessageMapImpl.java

Fixing https://wso2.org/jira/browse/MB-1512

[MB-1512] Prevent DISCARD ALLOWED strategy for durable topic messages

---

modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/AMQPUtils.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/QueueDeclareHandler.java

use "tmp_{randomUUID()}" when queue name is not given.
https://wso2.org/jira/browse/MB-1513

[MB-1513] Cannot declare a topic without specifying a topic name

---

modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/QpidAndesBridge.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/QueueDeclareHandler.java

Revert "[MB-1497] Made queue creation case insensitive"

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
modules/andes-core/management/common/src/main/java/org/wso2/andes/management/common/mbeans/QueueManagementInformation.java

Addresses the issue reported at https://wso2.org/jira/browse/MB-1511

[MB-1511] Removed delivery mode column from UI

---

modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesUtils.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/NameValidationUtils.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQTopic.java

Tracked by https://wso2.org/jira/browse/MB-1542

Colon issue for topic and queue names

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/AckHandler.java

Implement retrying message deletion on store failure

[MB-1527] Observed a message loss in a queue in a long running test

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/QueueDeleteHandler.java

Addresses the issue reported at https://wso2.org/jira/browse/MB-1545

[MB-1545] Prohibited deletion of DeadLetterChannel

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundQueueEvent.java

Tracked by https://wso2.org/jira/browse/MB-1555

Remove disruptor event wait timeout

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java

fixing issue : https://wso2.org/jira/browse/MB-1527
Issue was the lock scope if assigning a slot (giving a fresh slot and marking it as assigned should happen atomically)

[MB-1527]Fixed message duplication issue in cluster

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/SubscriptionManagementInformationMBean.java

When displaying shared durable subscriptions, display only active subscriptions. If there are no active shared subscriptions for a particular subscriber ID, then display only one inactive shared durable subscription for the same.

Filter shared durable inactive subscriptions when displaying from UI

---

modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java

also set default sync interval to 15 minutes.

moving vHostSyncTaskInterval under recovery tag

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotCoordinator.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotCoordinatorCluster.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotCoordinatorStandalone.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotCreator.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeleteSafeZoneCalc.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotMessageCounter.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/SlotAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/HazelcastAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/rdbms/DatabaseSlotAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingAndesContextStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/MBThriftClient.java
modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/SlotManagementServiceImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/slot/gen/SlotManagementService.java
modules/andes-core/broker/src/main/resources/slot.thrift

Initial commit for calculating local safe zone based on minimum ID across all destinations of a single node.

Fixing MB-1559

---

modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQConnectionDelegate_0_10.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQConnectionDelegate_8_0.java

jira: https://wso2.org/jira/browse/MB-1571

[MB 1571] Not all failed messages in the MB queue is not delivered to the BE service after failover

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/SubscriptionManagementInformationMBean.java
modules/andes-core/management/common/src/main/java/org/wso2/andes/management/common/mbeans/QueueManagementInformation.java
modules/andes-core/management/common/src/main/java/org/wso2/andes/management/common/mbeans/SubscriptionManagementInformation.java

Fixing https://wso2.org/jira/browse/MB-1490

Added necessary MBean exceptions to be thrown upon DB outage.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/HazelcastClusterAgent.java

**Retry node ID read when checking for duplicate node IDs**
This is done to avoid getting a Null pointer exception at startup
when multiple nodes are started paralley in the cluster.

 [MB1089] [Cluster] Hazelcast issue in server startup

---

modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/AndesConfigurationManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/util/ConfigurationProperty.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotMessageCounter.java

jira: https://wso2.org/jira/browse/MB-1584
This fixes the confusion around slotRetainTimeInMemory property in broker.xml

[MB-1584] Change slotRetainTimeInMemory property in broker.xml in to a meaningful name

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundDeleteDLCMessagesEvent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingMessageStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java

This addresses the issue reported at https://wso2.org/jira/browse/MB-1596

[MB-1596] Delete messages not in DLC when acknowledged

---

pom.xml

jira: https://wso2.org/jira/browse/MB-1561

[MB-1561]Upgrade carbon matrix lib

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/ConnectionException.java
modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/MBThriftClient.java
modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/exception/ThriftClientException.java

jira: https://wso2.org/jira/browse/MB-1599

[MB-1599] Coordinator node should be started first to start other nodes

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesRecoveryTask.java

JIRA - https://wso2.org/jira/browse/MB-1603

[MB-1603] Ignoring MQTT queues upon andes recovery task

---

modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/messaging/spi/impl/ProtocolProcessor.java
modules/andes-core/broker/src/main/java/org/dna/mqtt/wso2/AndesMQTTBridge.java
modules/andes-core/broker/src/main/java/org/dna/mqtt/wso2/MQTTSubscriptionStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTopicManager.java

Associated JIRA - https://wso2.org/jira/browse/MB-1606

Update mqtt subscriber received topic to have published destination instead of subscribed destination with wildcards

---

modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTopicManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionEngine.java

JIRA - https://wso2.org/jira/browse/MB-1572

[MB-1572] Removing existing durable mqtt subscriptions when the same client connects with clean session true.

---

modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/parser/netty/PublishDecoder.java

Changing the level of log to avoid printing it for each published message.

Fix for https://wso2.org/jira/browse/MB-1610

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionEngine.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionProcessor.java

JIRA - https://wso2.org/jira/browse/MB-1613
Reopening the pull https://github.com/wso2/andes/pull/519 with changes.

[MB-1613] Deleting queue and non-durable topic subscriptions upon restart.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTopicManager.java

… to rectify the issue of causing a Nullpointer for a fresh subscription. Will need to re think of solving the issue in a more efficient way

Rectifying the issue of causing a NullPointer when fresh subscription is created

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageExpirationWorker.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/ConnectionException.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotCreator.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeleteSafeZoneCalc.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorker.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorkerManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/StoreHealthCheckTask.java

Catch Throwable exceptions on critical tasks to avoid exception swallowing and eventually killing critical threads in MB.

Catch Throwable exceptions on critical tasks

---

modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AMQPMetaDataHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesMessageMetadata.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DisruptorCachedContent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/compression/LZ4CompressionHelper.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/ContentCacheCreator.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/ContentDecompressionHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DeliveryEventData.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DisruptorBasedFlusher.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/ContentChunkHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTMessageContext.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTMessageMetaData.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTMetaDataHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/connectors/PersistenceStoreConnector.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/utils/MQTTUtils.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/message/MessageMetaData.java
modules/andes-core/broker/src/main/java/org/wso2/andes/tools/utils/MessageTracer.java
modules/andes-core/pom.xml
modules/orbit/andes/pom.xml
pom.xml

Changes related to "adding compression to MB"
Please merge with: https://github.com/wso2/carbon-business-messaging/pull/242

[MB-1617] Adding lz4 compression to mb

---

modules/orbit/andes-client/pom.xml
modules/orbit/andes/pom.xml
pom.xml

jira: https://wso2.org/jira/browse/MB-1620

[MB-1620] upgrade guava libraries to v 19

---

modules/andes-core/pom.xml
pom.xml

This reverts commit b0b52dabf64955c92f9381d6c4fd9857bb185cc6.

Revert "Update lmax.disruptor version to 3.3.4"

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeletionExecutor.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorker.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java

When a member leaves the cluster schedule to delete all the empty slots of the left node.

Delete empty slots when a member leaves the cluster

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlledQueueMessageDeliveryImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageDeliveryInfo.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/NoLossBurstTopicMessageDeliveryImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/SlowestSubscriberTopicMessageDeliveryImpl.java

JIRA https://wso2.org/jira/browse/MB-1624

Fix for stale issue

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DeliveryEventHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DisruptorBasedFlusher.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundEventManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/MessagePreProcessor.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/StateEventHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionEngine.java
modules/andes-core/pom.xml
pom.xml

Need to enable it once a Metrics C5 release is done.

Metrics module commented out

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlledQueueMessageDeliveryImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageDeliveryStrategy.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageFlusher.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/NoLossBurstTopicMessageDeliveryImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/SlowestSubscriberTopicMessageDeliveryImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorker.java

Tracked by https://wso2.org/jira/browse/MB-1639

Resolved MB-1639 - Accumulates messages in durable topics even thoughactive subscriptions subscribed to the broker

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesRecoveryTask.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/HazelcastLifecycleListener.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/SubscriptionListener.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/HazelcastClusterAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/CoordinationConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/DatabaseSyncNotificationListener.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/HazelcastAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingAndesContextStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/LocalDurableTopicSubscriptionStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/QueueSubscriptionStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionEngine.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionProcessor.java
modules/andes-core/common/src/main/java/org/wso2/andes/pool/Job.java

Merging changes introduced for patch 0131 for MB 3.0.0 which fixes the following issues.
https://wso2.org/jira/browse/MB-1642
https://wso2.org/jira/browse/MB-1647
https://wso2.org/jira/browse/MB-1648

Patch0131 merge to master

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesRecoveryTask.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/HazelcastLifecycleListener.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/SubscriptionListener.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/HazelcastClusterAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/CoordinationConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/DatabaseSyncNotificationListener.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/HazelcastAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingAndesContextStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/LocalDurableTopicSubscriptionStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/QueueSubscriptionStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionEngine.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionProcessor.java
modules/andes-core/common/src/main/java/org/wso2/andes/pool/Job.java

Adding changes introduced in patch 0131 for MB 3.0.0 into C5 branch which fixes the following issues.
https://wso2.org/jira/browse/MB-1642
https://wso2.org/jira/browse/MB-1647
https://wso2.org/jira/browse/MB-1648

Patch0131 merge to c5

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageFlusher.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeleteSafeZoneCalc.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeletionExecutor.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorker.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQConnectionDelegate_8_0.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/protocol/HeartbeatDiagnostics.java

JIRA - 
https://wso2.org/jira/browse/MB-1652
https://wso2.org/jira/browse/MB-1651
https://wso2.org/jira/browse/MB-1650

[MB-1652,MB-1651,MB-1650] Adding identified fixes.

---

modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/messaging/spi/impl/ProtocolProcessor.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java

remove AMQPUtils reference when getting message content size.

[Code Refactoring] get content size in getRetainedMessageContent without using AMQPUtils

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorker.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorkerManager.java

Conflicts:
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorker.java

[MB-1653] Stop SlotDeliveryWorkers when there are no active subscribers.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java

JIRA - https://wso2.org/jira/browse/MB-1657

[MB-1657] Added improvement to rereoute messages of a specific destination in DLC to a queue.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java

Revert "[MB-1657] Added improvement to rereoute messages of a specific destination in DLC to a queue."

---

modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java

Revert "Revert "[MB-1657] Added improvement to rereoute messages of a specific destination in DLC to a queue.""

---

modules/andes-core/common/src/main/java/org/wso2/andes/pool/ReferenceCountingExecutorService.java

This reverts commit 492956a7cf44b748a67e260073e6ef2f865cc38b.

Revert "Revert "Add a name to the job pool thread""

---

modules/andes-core/common/src/main/java/org/wso2/andes/pool/ReferenceCountingExecutorService.java

Revert "Revert "Revert "Add a name to the job pool thread"""

---

modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesChannel.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlListener.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/HazelcastLifecycleListener.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/ContentCacheCreator.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DeliveryEventHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/ConnectionException.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorker.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotMessageCounter.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTPublisherChannel.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/connectors/PersistenceStoreConnector.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/AMQChannel.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/ClusterAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/HazelcastClusterAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/HazelcastAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/error/detection/DisabledNetworkPartitionDetector.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/error/detection/HazelcastBasedNetworkPartitionDetector.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/error/detection/NetworkPartitionDetector.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/error/detection/NetworkPartitionListener.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/LocalSubscription.java
modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/MBThriftClient.java

This is work in progress don't merge.

[MB-1664] Ability to detect Network partitions

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorker.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorkerManager.java

Fixe for issue https://wso2.org/jira/browse/MB-1671.

Wait for SlotDeliveryWorker to stop it's running thread before completing stop delivery

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/MessagePreProcessor.java

Jira : https://wso2.org/jira/browse/MB-1667

[MB-1667] fix issue in durable topic message delivery with compression enabled

---

modules/andes-core/client/src/main/java/org/wso2/andes/client/protocol/AMQProtocolHandler.java

Fixes the thread leak when connecting to unauthorized queue

Fix for issue MB-1670 : thread leak when connecting to unauthorized queue

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/OrphanedSlotHandler.java

This happens because the internal map "trackedSubscriptions" in OrphanedSlotHandler
does not have the subscribedNode as part of the key. This causes the newly failed
over subscription on MB2 node to be deleted from this map, which in return skips
the slot return logic when this subscription disconnects.
Note: Fix was done by @hastef88

Slots are not returned when disconnecting subscribers that have failed over from one MB node.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageDeliveryInfo.java

Replace ConcurrentHashMap with ConcurrentSkipListMap in MessageDeliveryInfo

Fix build failure

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/ProtocolType.java
modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionProcessor.java

Make the ProtocolType class final and pre-calculate the hashcode value and use the same in the equals method to make the operations faster.

Improve ProtocolType implementation.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/HazelcastLifecycleListener.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotCoordinatorCluster.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeletionExecutor.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorker.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/ClusterOutageException.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/error/detection/DisabledNetworkPartitionDetector.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/error/detection/HazelcastBasedNetworkPartitionDetector.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/error/detection/NetworkPartitionDetector.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/error/detection/NetworkPartitionListener.java
modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/MBThriftClient.java

jira: https://wso2.org/jira/browse/MB-1679

[MB-1679] Handle Hazelcast inactive error

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java

jira: https://wso2.org/jira/browse/MB-1691

[MB-1691] Delete Messages from DLC queue when using postgreSQL

---

modules/andes-core/broker/src/main/java/org/wso2/andes/qmf/QMFType.java
modules/andes-core/broker/src/xsl/qmf.xsl
modules/andes-core/common/genutil.py
modules/andes-core/common/src/main/java/org/wso2/andes/transport/codec/AbstractDecoder.java
modules/andes-core/common/src/main/java/org/wso2/andes/transport/codec/AbstractEncoder.java
modules/andes-core/common/src/main/java/org/wso2/andes/transport/codec/Decoder.java
modules/andes-core/common/src/main/java/org/wso2/andes/transport/codec/Encoder.java
modules/specs/amqp.0-10-qpid-errata.xml
modules/specs/amqp.0-10.xml

Addresses the issue reported at https://wso2.org/jira/browse/MB-1695

Added STR32 type to encode/decode Strings

---

modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQSession_0_8.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/BasicMessageConsumer.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/BasicMessageConsumer_0_10.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/DelayedObject.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/message/AMQMessageDelegate_0_8.java
modules/andes-core/client/src/main/java/org/wso2/andes/jms/Session.java

JIRA - https://wso2.org/jira/browse/MB-1687
This PR contains implementation for client side delivery delay for redelivered messages. The implementation uses a delayed queue(JAVA7) which delays redelivered messages.
The implementation for Per Message Acknowledgements are also included.

[MB-1687] Added implementation for client side redelivery delay.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java

Jira related : https://wso2.org/jira/browse/MB-1573

Show correlation ID and some JMS properties in the UI

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java

jira:https://wso2.org/jira/browse/MB-1702
Fix the bug of not deleting the expired messages in DLC from the database.

[MB-1702] DLC Message expiration fix

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundSubscriptionEvent.java

fixed : https://wso2.org/jira/browse/MB-1698

[MB-1698] Handle AndesException properly in waitForCompletion method

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/SlotAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/HazelcastAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/rdbms/DatabaseSlotAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingAndesContextStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingMessageStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java

Associated Jira: https://wso2.org/jira/browse/MB-1706

[MB-1706] Fix for Expiry Message Deletion when there is no subscription

---

modules/andes-core/broker-plugins/experimental/info/src/main/java/org/wso2/andes/info/AppInfo.java
modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/server/netty/metrics/SSLHandlerFactory.java
modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/modules/JKSStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/qpid/ServerConfiguration.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/Broker.java
modules/andes-core/broker/src/test/java/org/wso2/andes/server/configuration/ServerConfigurationTest.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQConnectionDelegate_8_0.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/SSLConfiguration.java

jira: https://wso2.org/jira/browse/MB-1705

[MB-1705] Remove hardcoded cert types from andes

---

modules/andes-core/broker-plugins/experimental/info/src/main/java/org/wso2/andes/info/AppInfo.java
modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/qpid/ServerConfiguration.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/Broker.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQConnectionDelegate_8_0.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/SSLConfiguration.java

jira: https://wso2.org/jira/browse/MB-1705

[MB-1705] Remove hardcoded cert types from andes C5

---

modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/AMQPUtils.java
modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/QpidAndesBridge.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/QueueBrowserDeliveryWorker.java

Fix naming convention violations

Fix naming issues with getMessageId method

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextInformationManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DestinationType.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlledQueueMessageDeliveryImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/NoLossBurstTopicMessageDeliveryImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/SlowestSubscriberTopicMessageDeliveryImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/router/AndesMessageRouter.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/router/MQTTMessageRouter.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/router/QueueMessageRouter.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/router/TopicMessageRouter.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscription.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/InactiveSubscriber.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/StorageQueue.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/connectors/PersistenceStoreConnector.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/SubscriptionManagementInformationMBean.java
modules/andes-core/management/common/src/main/java/org/wso2/andes/management/common/mbeans/SubscriptionManagementInformation.java

Add the subscription filtering logic using CQengine queries

Add subscription filtering

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java

jira: https://wso2.org/jira/browse/MB-1739

[MB-1739] Unable to view messages in the DLC when more than 100 messages exists

---

modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/messaging/spi/impl/ProtocolProcessor.java

jira: https://wso2.org/jira/browse/MB-1716

[MB-1716] Null pointer exception is thrown when an unauthenticated client is subscribing to mqtt topic

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscriptionManager.java

Add whole cluster instances wide filtering query
Associated JIRA Link: https://wso2.org/jira/browse/MB-1778

[MB-1778] Add cluster wide subscription filtering

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java

Addresses the issue reported at https://wso2.org/jira/browse/MB-1789

[MB-1789] fixed issue when storing messages

---

modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/QpidAndesBridge.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/SubscriptionManagementInformationMBean.java
modules/andes-core/management/common/src/main/java/org/wso2/andes/management/common/mbeans/SubscriptionManagementInformation.java

Fix subscription filtering for durable topics and fix the refresh button.
Associated JIRA Link:  https://wso2.org/jira/browse/MB-1778
https://wso2.org/jira/browse/MB-1790

[MB-1790][MB-1778]Fix Subscription filtering and Refresh button

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlledQueueMessageDeliveryImpl.java

https://wso2.org/jira/browse/MB-1795
https://wso2.org/jira/browse/MB-1798

[MB-1795] Copy currentSubscriptions list before using it to deliver messages

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/binding/BindingFactory.java

This issue happens when adding subscribers to multiple nodes in the cluster concurrently. 
Fixing : 
https://wso2.org/jira/browse/MB-1801
https://wso2.org/jira/browse/MB-1792

Fixed deadlock issue when adding subscribers 

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/SubscriberConnection.java

Fix hard coded value for maxNumberOfMessagesToKeepInMemory. Now reading from config.

Fix hard coded value for maxNumberOfMessagesToKeepInMemory

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java

Addresses the issue reported at https://wso2.org/jira/browse/MB-1808

Added db connection close

---

modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/AMQPLocalSubscription.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesRecoveryTask.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/AckHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/MessageWriter.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotMessageCounter.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/ClusterManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingAndesContextStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingMessageStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingStoreManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/StoreHealthCheckTask.java

Addresses the issue reported at https://wso2.org/jira/browse/MB-1727

[MB-1727] - Subscriptions don't become inactive once the db connection is dropped and restored

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscriptionManager.java

Public jira : https://wso2.org/jira/browse/MB-1809

Fixed MB-1809

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/queue/DLCQueueUtils.java

Addresses the issue reported at https://wso2.org/jira/browse/MB-1784

[MB-1784] - Incorrect DLC name for durable subscriptions in tenants

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscription.java

Fixing https://wso2.org/jira/browse/MB-1822.

[MB-1822] Fixed null pointer issue when closing subscribers.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/AMQChannel.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/connection/ConnectionRegistry.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQConnection.java

- Add try finally block to avoid channel close getting blocked
- Deregister connections when close call failed remove the connection
- Fix race condition issue on failover mutex when closing publisher
while receiving exceptions

Fix MB-1811

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesMessageMetadata.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DLCExpiryCheckEnabledDeletionTask.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DLCMessageExpiryManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DefaultMessageExpiryManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DeliveryMessageHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DeliveryResponsibility.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DestinationType.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/ExpiredMessageHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageFlusher.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/PeriodicExpiryMessageDeletionTask.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/PreDeliveryExpiryMessageDeletionTask.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/PurgedMessageHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/AbstractSlotManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerStandalone.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/HazelcastAgent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/SubscriptionManagementInformationMBean.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/tools/utils/MessageTracer.java
modules/andes-core/management/common/src/main/java/org/wso2/andes/management/common/mbeans/SubscriptionManagementInformation.java

refactor code

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java

Addresses the issue reported at https://wso2.org/jira/browse/MB-1835

[MB-1835]-Fixed issue in RDBMS based router sync

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorkerManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscription.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/StorageQueue.java
modules/andes-core/broker/src/main/java/org/wso2/andes/task/TaskExecutorService.java

https://wso2.org/jira/browse/MB-1743

[MB-1743] Add a method to SDW to wait until termination

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/RecoverySlotCreator.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotCreator.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingMessageStore.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java

Fetch result set from the database once and iterate while recovering slots eliminating multiple database calls.
jira : https://wso2.org/jira/browse/MB-1846

[MB-1846] Optimize mb slot recovery process during startup

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextInformationManager.java

Fixes the issues reported at https://wso2.org/jira/browse/MB-1845 and https://wso2.org/jira/browse/MB-1849

[MB-1845] Fixed messages remianing when non-durable subscriber is disconnected

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
modules/andes-core/management/common/src/main/java/org/wso2/andes/management/common/mbeans/QueueManagementInformation.java

Fix the NPE when to reroute/restore the expired messages from DLC
Associated JIRA Link: https://wso2.org/jira/browse/MB-1829
Merge with https://github.com/wso2/carbon-business-messaging/pull/364

[MB-1829] Fix reroute/restore expired messages from DLC

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundKernelOpsEvent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/MBThriftServer.java

jira: https://wso2.org/jira/browse/MB-1770

[MB-1770] stop thrift server when shutdown call is received

---

modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/QpidAndesBridge.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextInformationManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundQueueEvent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/StorageQueue.java

Fixing https://wso2.org/jira/browse/MB-1860

[MB-1860]Queue delete and purge in non durable path

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/router/TopicMessageRouter.java

Fixes the issue reported at https://wso2.org/jira/browse/MB-1850

[MB-1850] messages stored after durable subscription unsubscribes

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesMessageMetadata.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DeliveryResponsibility.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/ExpiredMessageHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageExpiryManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/PreDeliveryExpiryMessageDeletionTask.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/PurgedMessageHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/router/MQTTMessageRouter.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/connectors/PersistenceStoreConnector.java

Code refactor

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/QueueBrowserDeliveryWorker.java

https://wso2.org/jenkins/view/All%20Builds/job/andes/1411/consoleFull#196672687058229558e4b05d3853a6a501

Correct jenkins build failure

---

modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/CoordinatorConnectionListener.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotCoordinator.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotCoordinatorCluster.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotCoordinatorStandalone.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorkerManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/MBThriftClient.java
modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/ThriftClientFactory.java
modules/andes-core/pom.xml
pom.xml

Fix https://wso2.org/jira/browse/MB-1869.
Add a thrift connection pool and remove static behaviour of the thrift client.

[MB-1869] Add a connection pool to thrift client

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/protocol/AMQProtocolEngine.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/handler/ChannelCloseMethodHandler.java
modules/andes-core/common/src/main/java/org/wso2/andes/protocol/AMQConstant.java

This will notify andes client when a durable subscription closed from management UI console.
**IMPORTANT:** Make sure log4j is properly configured with the client.
Jira : https://wso2.org/jira/browse/MB-1858

[MB-1858] Notify channel close status to the client.

---

modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQSession.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/BasicMessageConsumer.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/protocol/AMQProtocolHandler.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/protocol/BlockingMethodFrameListener.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/util/BlockingWaiter.java

JIRA: https://wso2.org/jira/browse/MB-1876

Fix multiple durable subscribers with same subscription Id test failure

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/dtx/DistributedTransaction.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/dtx/DtxBranch.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/dtx/DtxRegistry.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/AMQChannel.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/txn/QpidDistributedTransaction.java

- Use AndesAckData#getChannelId method to get the channel Id

Remove dtx.rollback method channel Id argument

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextInformationManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/ClusterManager.java

Fixes the issue reported at https://wso2.org/jira/browse/MB-1878

[MB-1878] Fixed incorrect local subscription removed log

---

modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java

- transaction/maxBatchSizeInKB : 1024 -> 10240
- transaction/maxParallelDtxChannels : 100 -> 10

Change transaction config defaults

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/RDBMSCoordinationStrategy.java

Enable rdbmsBasedCoordination and RDBMSBasedClusterEventSynchronization caused thrift exception at server startup when electing coordinator. The problem is we are starting thrift server regardless of coordinator election. This fix is to wait until coordinator election completed and then start thrift server.

Fix for MB-1880

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java

Addresses the issue reported at https://wso2.org/jira/browse/MB-1885

MB-1885 Exception thrown in subscriptions page in oracle

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextInformationManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/StorageQueue.java

Addresses the issue reported at https://wso2.org/jira/browse/MB-1888

[MB-1888] fixed issue in purge notification handling

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextInformationManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/StorageQueue.java

Refactored changes that were done in https://github.com/wso2/andes/pull/820/files
Message deletion from the database was moved inside the storage queue.

Refactor changes in #820

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java

Renamed dtx tables that are changed by https://github.com/wso2/carbon-business-messaging/pull/417

Renamed dtx tables

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscription.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java

Fixes the issue reported at https://wso2.org/jira/browse/MB-1904
The failure of the addition of a single binding/subscription should not block the rest being added.

[MB-1904] Fixed issue in db sync

---

modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/AndesConfigurationManager.java

Porting fix : https://github.com/wso2/andes/pull/777

Ei compatibility fixes

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/logging/management/LoggingManagementMBean.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/security/auth/database/Base64MD5PasswordFilePrincipalDatabase.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/security/auth/database/PlainPasswordFilePrincipalDatabase.java

According to FindBugs 
_Value java.util.Random
Predictable pseudorandom number generator. The use of java.util.Random is predictable_
Fixed by using SecureRandom.

Add secureRandom generator which is more secured

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/dtx/DistributedTransaction.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/dtx/DtxBranch.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/dtx/DtxRegistry.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/AMQChannel.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/txn/QpidDistributedTransaction.java

The issue is fixed by using AMQChannel's ID for transaction association.

Fix MB-1925

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundMessageRecoveryEvent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscription.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/StorageQueue.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/SubscriberConnection.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/AMQChannel.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/ChannelFlowHandler.java

Fixes issues in message recovery which caused the failure of test cases. Tracked at https://wso2.org/jira/browse/MB-1927

[MB-1927] Fix failing recovery tests

---

modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/messaging/spi/impl/UserAuthenticator.java
modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/AndesConfigurationManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesAckEvent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesUtils.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DeliveryEventHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DisruptorBasedFlusher.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundEventManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/MessagePreProcessor.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/StateEventHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscription.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/utils/MQTTUtils.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/ClusterResourceHolder.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/Main.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/HazelcastCoordinationStrategy.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/queue/DLCQueueUtils.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/security/auth/manager/CarbonBasedPrincipalDatabase.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/security/auth/sasl/plain/PlainSaslServer.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingStoreManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConnection.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java
modules/andes-core/client/src/main/java/org/wso2/andes/jndi/PropertiesFileInitialContextFactory.java
modules/andes-core/pom.xml
modules/orbit/andes/pom.xml
pom.xml

- Disabled MQTT
- Disabled Authentication

Update for Carbon 5 migration

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundEventContainer.java

Issue: https://github.com/wso2/product-ei/issues/865

Clear AndesChannel after processing in Disruptor

---

modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQConnectionFactory.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQXAConnectionFactory.java
modules/andes-core/client/src/main/java/org/wso2/andes/jndi/PropertiesFileInitialContextFactory.java
modules/andes-core/systests/src/main/java/org/wso2/andes/test/unit/xa/FaultTest.java
modules/andes-core/systests/src/main/java/org/wso2/andes/test/unit/xa/QueueTest.java
modules/andes-core/systests/src/main/java/org/wso2/andes/test/unit/xa/TopicTest.java
modules/andes-core/systests/src/main/java/org/wso2/andes/test/utils/QpidBrokerTestCase.java

Resolves : https://github.com/wso2/product-ei/issues/847

EI-847 Separate out the XA connection factory

---

modules/andes-core/broker-plugins/firewall/MANIFEST.MF
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscriptionManager.java

Display MQTT related topics, subscription and message details. Implemented MQTT Admin service and service stub

Changing MQTT message router value

---

modules/andes-core/broker-plugins/firewall/MANIFEST.MF

Defined version range for com.googlecode.cqengine

Modifying MANIFEST.MF

---

modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQXAConnectionFactory.java

There were some issues, missed method implementations in the feature. Completed
them so that XA scenarios work with web-logic server etc.

Fix EI-847 - Separate out the XA connection factory impl

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscription.java

> Resolves https://github.com/wso2/product-ei/issues/985.
> Properly split the encoded connection string.
> Enforce the string split limit of the encoded connection string to avoid splitting the string incorrectly.

Fix https://github.com/wso2/product-ei/issues/985.

---

modules/andes-core/client/src/main/java/org/wso2/andes/client/protocol/AMQProtocolHandler.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/protocol/BlockingMethodFrameListener.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/util/BlockingWaiter.java
modules/andes-core/pom.xml
modules/orbit/andes-client/pom.xml
modules/orbit/andes/pom.xml
pom.xml

Update mina version to forked repo version which contains a fix for https://github.com/wso2/product-ei/issues/1242

Update mina version to forked repo version

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java

Remove commented code

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DeliveryEventHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/MessagePreProcessor.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/StateEventHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscription.java

This fixes metric names for Send and Receive Messages and Send and Receive Acknowledgement metrics 
> Link to the PR for changes …

Fix metric names for Send and Receive metrics

---

modules/andes-core/client/src/main/java/org/wso2/andes/client/BasicMessageProducer_0_8.java

- Send AMQP exchange.declare frame from andes client with passive bit set for built in exchanges.

Fix AMQP exchange declare invocation

---

pom.xml

Upgrade mina version to the latest version.
Incorporate latest fixes done in mina.
Upgrade mina version to the latest version containing the latest fixes.
N/A
N/A
N/A
N/A
N/A
N/A
N/A
N/A
wso2/wso2-mina/pull/8
N/A
N/A
N/A

Upgrade mina version to 1.1.7-wso2v3

---

modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQSession.java

Remove isQueueBound method since It violates the AMQP Spec by sending Class 40 with Method 22 frame packet
Fix https://github.com/wso2/message-broker/issues/110
> Link to the PR for changes to the training content in …

Remove isQueueBound method usages

---

modules/orbit/andes-client/pom.xml
pom.xml

The version range of the commons-lang.imp.pkg.versio in andes client isn't defined in the parent pom which cause not to resolve the version range porperly in the imports. And upgrade the guava version of the client.
> Link(s) to product documentation that addresses the changes of this …

Adding missing commons import range and guave version upgrade

---

modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/MBThriftClient.java

> Fix wso2/product-ei/issues/1716
> Improve thrift connection pooling to consider thriftSOTimeout parameter specified in broker.xml file
> Use timeout functionality comes with apache.commons.pool2.BaseGenericObjectPool class to achieve thiriftConnectionTimeout
> https://github.com/wso2/andes/pull/948/files#diff-e9c6470a462219b6ca0a6b8d6f886c96L80

Fix wso2/product-ei/issues/1716

---

modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/SlotManagementServiceImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/ThriftClientFactory.java
modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/slot/gen/SlotManagementService.java

> Fix product-ei/issues/1716
> Introduce health-check mechanism for connections taken from thrift connection pool
> Connections taken from thrift connection pool could be expired. This fix introduce a health-check mechanism (bogus thrift call) to update the thrift connections, so that they will not be expired at the point of using to the intended purpose.
> [https://github.com/wso2/andes/pull/955/](https://github.com/wso2/andes/pull/955/)
> JDK8, Ubuntu 16.04

Fix product-ei/issues/1716

---

modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorkerManager.java

Task idle time set to 100ms in the SlotDeliveryWorkerManager. This fix is to externalize the config value. 
Resolves: https://github.com/wso2/product-ei/issues/1826
Decreasing task idle time will effect on speed up delivery messages when publishers are slow. But system load will go up.
For an example change `<idleTaskDelay>10</idleTaskDelay>` in the broker.xml under `<slots>`
A user wants to gain subscribers performance when publishers are slow.
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if …

fix product-ei/issues/1826

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/MessageDeliveryTask.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/StorageQueue.java

> Fix wso2/product-ei/issues/1865
> Remove redundant message buffer cleanup

Fix wso2/product-ei/issues/1865

---

modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/ThriftClientFactory.java

> Fix wso2/product-ei/issues/1883
> Changing the log level since the exception is occuring in a health-check mechanism

Fix wso2/product-ei/issues/1883

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesRecoveryTask.java

This fixes the subscription duplicate issue when store(DB) is down in clustered mode.
Issue - https://github.com/wso2/product-ei/issues/1885
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no …

Fix subscription duplicate issue when store is down

---

modules/andes-core/client/src/main/java/org/wso2/andes/client/message/AMQMessageDelegate_0_8.java

Avoid restricting JMS properties in AMQP_STRICT mode since field tables can be used for this purpose.
> Describe the solutions that this feature/fix will introduce to resolve the problems described 
Allow using JMS properties with AMPQ_STRICT mode.
Remove respective checks in message delegate class.
N/A
> Brief …

Avoid restricting JMS properties in AMQP_STRICT mode

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java

When rerouting messages with content and without content from DLC a NPE is thrown(When messageParts are null)
Fixes:wso2/product-ei#1915
> Brief description of the new feature or bug fix as it will appear in the …

 Fix NPE thrown when rerouting messages from DLC

---

modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/ThriftClientFactory.java

> Fix 7c396cd67b9f2397bb3b9dd3cada68217df44227
> Link to the PR for changes to the training content in …

Fix previous PR

---

modules/andes-core/common/src/main/java/org/wso2/andes/common/QpidProperties.java

Avoid printing a warning for qpid.properties file

Avoid printing a warning for qpid.properties file

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundMessageRecoveryEvent.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQConnection.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQConnectionDelegate_8_0.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQSession.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/failover/FailoverHandler.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/protocol/AMQProtocolHandler.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/protocol/HeartbeatDiagnostics.java
modules/andes-core/common/src/main/java/org/wso2/andes/transport/network/mina/MinaNetworkConnection.java

We have identified some issues in ESB + MB integration scenarios such as local transaction and failover.  This PR has set of fixes for each problem.
Resolves https://github.com/wso2/product-ei/issues/2208
> Brief …

Fix issues in MB + ESB integration

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscriptionManager.java

Durable subscription failed to connect after database recovery fixed with this PR. This is a race condition that came with MSSQL. We found that `clusterNotificationAgent#notifySubscriptionsChange` doing some database in the subscriber close event. So moved it to if `(!storeUnavailable)`. For the safer side, move `storageQueue#unbindSubscription` to the same block because we use RDBMS based coordination.
Resolves: https://github.com/wso2/product-ei/issues/2220
> Describe how you are implementing the solutions. Include an animated GIF …

Fix product-ei/issues/2220

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java

Thrift communication failed in Kubernetes environment because pod name set as the hostname. This is changed to get the IP and persist in the MB_COORDINATOR_HEARTBEAT table instead of hostname. 
Resolves: https://github.com/wso2/product-ei/issues/2259
> Summary of user …

Fix product-ei/issues/2259

---

modules/andes-core/client/src/main/java/org/wso2/andes/client/TopicPublisherAdapter.java
modules/andes-core/common/src/main/java/org/wso2/andes/AMQChannelClosedException.java

Change AMQChannelClosedException hardError state to false, so that connection closed state will be false at AMQChannelClosedException (403) from the JMS application level.
Fix https://github.com/wso2/product-ei/issues/2341
> Link(s) to product documentation that addresses the changes …

Fix product-ei#2341

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextInformationManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscriptionManager.java

This is race condition due to sudden member leave and joins to the cluster. Storage queue becomes null because of cluster notification send to remove the subscription and queue information. This avoided checking active subscription is exists at the time of queue delete event sync. Same way binding event sync also ignores binding deletion if there is active subscription.
Resolves https://github.com/wso2/product-ei/issues/2356
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects …

Fix product-ei/issues/2356

---

modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/server/netty/metrics/SSLHandlerFactory.java
modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/Broker.java
modules/andes-core/common/src/main/java/org/wso2/andes/ssl/SSLContextFactory.java
modules/andes-core/common/src/main/java/org/wso2/andes/transport/network/mina/MinaNetworkHandler.java

Enable SSL protocols and preferred cipher suties for AMQP and MQTT transports in WSO2 MB.
Fix https://github.com/wso2/product-ei/issues/2365
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no …

Fix product-ei#2365

---

modules/andes-core/client/src/main/java/org/wso2/andes/client/protocol/AMQProtocolHandler.java

We need to close the stale connections created due to the failover process failing. This is done to avoid connection leaks.

Explicitly try to close the connection after a failover failure

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/subscription/SubscriptionImpl.java

The broker goes 'Out of Memory' when the database connection is dropped
and re-connected while the broker is connected to active subscriptions.
Once the databse is marked as non-operational, local subscriptions are
forcefully disconnected and message delivery to those are stopped.
Here, the main issue was that the bindings of those subscriptions were
not correctly removed when the subscriptions were disconnected thus
causing the broker to be trying to deliver messages to a subscriber
which is disconnected once the database becomes operational. Since the
underlying channel is closed, the deliver fails. Also, each time
messages are scheduled to be delivered to the subscription, they are
added to a map marking the delivery and these are not removed when a
delivery failure happens.
Resolves: …

Fix product-ei#2388

---

pom.xml

Update kernel version to 4.4.33 for release

Update kernel version for release

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorkerManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotMessageCounter.java

Set slot coordinator reference within SlotMessageCounter object after initialising the SlotCoordinator.
Issue: wso2/product-ei#2404
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …

Fix product-ei/issues/2404

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java

When a cluster gets killed, node-specific queues and bindings could be left in the database. If we don't clear them in a cluster restart messages can accumulate in the node-specific queues. Therefore this
commit clears all node-specific queue and binding state when restarting the cluster.
Resolves https://github.com/wso2/product-ei/issues/2424

Clear node specific queue in cluster restart

---

pom.xml

> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation …

Upgrade mina version

---

modules/andes-core/client/src/main/java/org/wso2/andes/jms/failover/FailoverRoundRobinServers.java

- Fix https://issues.apache.org/jira/browse/QPID-4549

Fix https://issues.apache.org/jira/browse/QPID-4549

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSDtxStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java

Resolves https://github.com/wso2/product-ei/issues/2672

Commit on select statements

---

modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQSession.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/BasicMessageConsumer.java
modules/andes-core/client/src/main/java/org/wso2/andes/client/BasicMessageConsumer_0_10.java

On rollback, underlying client queue is not cleared. AMQP Rejects are sent only to already consumed (but not committed)  messages.
Issue: https://github.com/wso2/product-ei/issues/2548
> Brief description of the new …

Fix for #ei-2548

---

modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/QpidAndesBridge.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundSubscriptionEvent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscriptionManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/queue/SimpleAMQQueue.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java

> Change error handling mechanism for DB disconnect scenarios.
> MB should be able to recover from DB disconnect / reconnect scenarios gracefully.
> Handle DB connection errors gracefully

Fix wso2/product-ei/issues/2864

---

modules/andes-core/client/src/main/java/org/wso2/andes/client/url/URLParser.java

> Fixes wso2/product-ei/issues/3010
> Resolve secrets in an AMQP url Ex:- {secretAlias:example}
> Introduce secret resolving mechanism via secure vault
> User need to resolve the complete AMQP url using secure vault
connectionfactory.QueueConnectionFactory = secretAlias:amqp.url
> User need to resove certain parts of the url from the secure vault
connectionfactory.TopicConnectionFactory = amqp://{secretAlias:amqp.username}:{secretAlias:amqp.pw}@clientID/carbon?brokerlist='tcp://localhost:5675'
> [Enabling SSL support](https://docs.wso2.com/display/EI630/Enabling+SSL+Support)

Add secret alias support in amqp url.

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesMessageMetadata.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java

> Log the message metadata that was tried to insert into the DB at an error.

Log message metadata when db error

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageStatus.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/NoLossBurstTopicMessageDeliveryImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscription.java

Fixes [wso2/andes#1005](wso2/andes#1005)

Fix invalid message state transition

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/registry/StorageQueueRegistry.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/DurableTopicSubscriptionInformationMBean.java
modules/andes-core/management/common/src/main/java/org/wso2/andes/management/common/mbeans/DurableTopicSubscriptionInformation.java

> Fixes : wso2/product-ei#3231

Introduce JMX attribute for message count of durable topic subscriptions

---

pom.xml

Update carbon-kernel version to 4.4.37

Update carbon-kernel version

---

modules/andes-core/lib/poms/commons-codec-1.12.xml
pom.xml

Upgrade kernel and commons-codec version

Upgrade Versions

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/registry/StorageQueueRegistry.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/DurableTopicSubscriptionInformationMBean.java

> Fixes : https://github.com/wso2/product-ei/issues/3452

Remove 'carbon:' from durable topic subscription mbean name

---

modules/andes-core/pom.xml
pom.xml

https://github.com/wso2/product-ei/issues/3436

Remove gson ependency which is not used

---

modules/andes-core/client/src/main/java/org/wso2/andes/client/protocol/HeartbeatDiagnostics.java

Reverts 8ef430a725e18b395cfc844d02409db69a5d0570
> Link(s) to product documentation that addresses the changes of this PR. If …

Revert enabled heartbeat diagnostics 

---

modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/AndesConfigurationManager.java
modules/andes-core/client/src/main/java/org/wso2/andes/jndi/PropertiesFileInitialContextFactory.java
pom.xml

> Secure vault changes and JDK 11 changes

Add JDK11 and Secure Vault changes

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextInformationManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundSubscriptionSyncEvent.java

Adding queue and binding to syncQueueDelete.
Fixes: wso2/product-ei#4415

Add queue and binding to syncQueueDelete

---

modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQBrokerDetails.java

Enables log masking for sensitive data in andes logs.
> Resolves [#4359](https://github.com/wso2/product-ei/issues/4359)

Fix product-ei#4359

---

pom.xml

Update kernel and metrics versions

Update kernel and metrics versions

---

pom.xml

> This PR will update dependency versions for kernel upgrade(4.5.3).

Update dependency versions for kernel upgrade(4.5.3)

---

modules/andes-core/client/src/main/java/org/wso2/andes/jndi/PropertiesFileInitialContextFactory.java
modules/andes-core/client/src/main/java/org/wso2/andes/jndi/Utils.java

This PR adds environment variable and system property support for jndi.properties file.
Fixes https://github.com/wso2/micro-integrator/issues/1183

Add environment variable support for jndi.properties file

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java

This PR is to fix https://github.com/wso2/product-ei/issues/5053
This PR is to fix https://github.com/wso2/product-ei/issues/5053

Fix EI-5053 Issue in setting TTL value to the published message

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesRecoveryTask.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DeliveryExceptionHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/rdbms/DatabaseSlotAgent.java

The PR fixes the issue mentioned in the below Github issue.
Resolves https://github.com/wso2/product-ei/issues/5248
> Link(s) …

Fix some messages not delivered after recovering from a db failure

---

modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesChannel.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlManager.java
modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/MBThriftServer.java

Resolves: https://github.com/wso2/product-ei/issues/5310 and https://github.com/wso2/product-ei/issues/5322 in a MB clustered setup
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc …

Fix dead lock and large number of thrift server workers

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java

The MSSQL database deadlock occurred with the cascade delete in the MB_CONTENT table. The PR has fixed that issue by deleting records from MB_CONTENT and MB_METADATA tables as a transaction.
Resolves https://github.com/wso2/product-ei/issues/5234
> Summary of user …

Fix deadlock in cascade delete

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotMessageCounter.java

Fix the race condition occurs when publishing messages to a message store slowly with the following parameter set to true.
`<parameter name="store.producer.guaranteed.delivery.enable">true</parameter>`
Fixes https://github.com/wso2/product-ei/issues/5276

Fix the race condition in the message publishing process

---

modules/andes-core/build.xml

Removing commented module

---

modules/andes-core/build.xml

Removing testkit module

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSDtxStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java
modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSStoreUtils.java

This PR adds the changes required with the fixes done in https://github.com/wso2/carbon-business-messaging/pull/712

Do required blob changes

---

modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/server/netty/NettyChannel.java
modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/server/netty/metrics/BytesMetricsHandler.java
modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/server/netty/metrics/MessageMetricsHandler.java
modules/andes-core/pom.xml
pom.xml

Update netty-all to the 4.1.77.wso2v1

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/NoLossBurstTopicMessageDeliveryImpl.java

Fix Getting ConcurrentModificationException.
Resolves: https://github.com/wso2/api-manager/issues/2283

Fix concurrent modification exception

---

modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java

- Add cache invalidation when queues are deleted from database
- Move the queue cache loader method and its supporting functions to a separate inner class.

Fix queue mapping cache handling issues

---

pom.xml

> Update commons-codec version to 1.16.0

Update commons-codec to 1.16.0

---

modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesAckEvent.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/AckHandler.java
modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/StateEventHandler.java

To add improvements in handling the null pointer exception from the Andes side.
Fixes: https://github.com/wso2/api-manager/issues/2508
Introduced code changes to handle potential null pointer exceptions throwable locations.

Improvements to handle NPE throwable flows

---

modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/rdbms/DatabaseSlotAgent.java

Fix messages getting stuck in durable topics after DB recovery
Fixes: https://github.com/wso2/micro-integrator/issues/3266

Fix messages getting stuck in durable topics after DB recovery

---

pom.xml

Fix jenkins build issues
