- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/HasInterestRule.java
$subject it will just create a big log file.
> Minor change - If the message is not selected by a jms selector we should not print a warning.

- modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/InboundQueueEvent.java
Fixing a null pointer exception while deleting a queue from UI, fixing a subscription related bug
> Fixing a null pointer exception while deleting a queue from UI, fixing a subscription related bug

- modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/qpid/ConfigStore.java
Changes are compatible with both jdk 1.8 and jdk 1.6
> [MB-958] Fixing the problems with the build of andes with oracle jdk 1.8

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/OrphanedMessageHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/DisruptorBasedInboundEventManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/InboundKernelOpsEvent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/InboundSubscriptionEvent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorker.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerStandalone.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotMessageCounter.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/Broker.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/ClusterManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/HazelcastAgent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/management/JMXManagedObjectRegistry.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java
- modules/andes-core/common/src/main/java/org/wso2/andes/transport/network/mina/MinaNetworkHandler.java
Handling exceptions occurring during server shutdown. Utilize Carbon ShutdownEventListener to close any isolated worker threads (e.g. SlotManager).
Handle HazelcastInstanceNotActiveException
> Fix Jiras 964 and 970

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AMQPConstructStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextInformationManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageCountFlusher.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/AMQBrokerManagerMBean.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/CQLBasedAndesContextStoreImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/CQLBasedMessageStoreImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorBasedMessageStoreImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/h2/H2MemMessageStoreImpl.java
- modules/andes-core/broker/src/test/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImplTest.java
Message count is directly taken from the DB instead of using the `AndesContextStore` message counters when using RDBMS message store
For Cassandra we need counters to keep track of message counts. This is done in `AndesContextStore`. But for RDBMS we can retieve message counts directly through and SQL query without counting separatly through `AndesContextStore`.
JIRA: https://wso2.org/jira/browse/MB-979
> Improvement for queue message count in RDBMS message store 

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/delivery/ContentCacheCreator.java
When an empty https://docs.oracle.com/javaee/6/api/javax/jms/TextMessage.html is published, the "ContentCacheCreator" is giving a null exception.
> Allowed empty messages to be received to the subscriber.

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/AckHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/AndesInboundStateEvent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/BatchEventHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/ConcurrentBatchEventHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/DisruptorBasedInboundEventManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/InboundAndesChannelEvent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/InboundBindingEvent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/InboundDeleteMessagesEvent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/InboundEventContainer.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/InboundExchangeEvent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/InboundKernelOpsEvent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/InboundLogExceptionHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/InboundQueueEvent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/InboundSubscriptionEvent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/MessagePreProcessor.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/MessageWriter.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/StateEventHandler.java
- Each state change related implementation class has its own state management.
Removed state information inheritance from AndesInboundStateEvent
interface.
- InboundEvent class renamed to InboundEventContainer. This works as a
container not as an event object
> State event related classes updated

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/ClusterManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/SubscriptionManagementInformationMBean.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/BasicSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java
The PR contains a fix for durable topics when it comes to fail-over. When a node is killed, the durable subscription is kept active by "hasExternalSubscriber" being true, therefore when the fail-over subscriber attempts to reconnect, it mentions that the subscriber is active.
JIRA - https://wso2.org/jira/browse/MB-703
> [MB-703] - Deactivating durable subscription when node is killed.

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/InboundKernelOpsEvent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/Broker.java
- modules/andes-core/systests/src/main/java/org/wso2/andes/test/utils/InternalBrokerHolder.java
Kernel operations such as shutdown Andes, shutdown message delivery can be done in a blocking manner with this fix
Jiras 
- https://wso2.org/jira/browse/MB-1021
- https://wso2.org/jira/browse/MB-1020
> Andes kernel operations converted to blocking calls

- modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/CQLBasedMessageStoreImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorBasedMessageStoreImpl.java
this PR will remove not implemented exceptions in retain related methods and add suitable empty lists/ maps until retain feature tested in cassandra.
> Remove exceptions in retain related methods implemented for cassandra datasource

- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/ClusterManager.java
If coordinator is not on the killed node then the coordinator
should try to recover any un submitted slots from the killed node.
> Fix for MB-1066

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/AMQPUtils.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesMessage.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesMessageMetadata.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DisruptorCachedContent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/delivery/ContentCacheCreator.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/delivery/DisruptorBasedFlusher.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/ContentChunkHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/DisruptorBasedInboundEventManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/distruptor/inbound/InboundEventContainer.java
- modules/andes-core/broker/src/test/java/org/wso2/andes/kernel/distruptor/inbound/ContentChunkHandlerTest.java
There is a new set of handlers added to the inbound disruptor ring to resize content chunks if needed. After that MessagePreProcessor will clone messages if necessary.
This will fix MQTT support for large messages as well. 
Jiras: 
https://wso2.org/jira/browse/MB-972
https://wso2.org/jira/browse/MB-1015
https://wso2.org/jira/browse/MB-1039
https://wso2.org/jira/browse/MB-1071
> Content chunking support for Andes core

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/AMQPUtils.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/Broker.java
Queue browser delivery worker content reading logic had a hard-coded constant value for max content chunk size. Updated this to reflect Andes max content chunk size.
Jira: https://wso2.org/jira/browse/MB-1100
> Large content view issue fixed

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
Initialize the current node ID as the removed node in SlotManager. This is
to avoid slot recovery task adding an empty node ID to the map used to calculate safe zone.
> Assign a default value to remove node value.

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/ClusterManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/HazelcastAgent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/rdbms/RDBMSAgent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
Fixing RDBMS query to return the slots when a node is killed. Fixing slot return when coordinator itself is killed. Failover happened successfully without message loss. At times several messages came again as acks did not reach sever at the time of killing, which is acceptable.
> Fixing message loss during node kill - failover testing

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/OnflightMessageTracker.java
We need to reduce non ack message count during message reject. Otherwise after a certain number of messages a client ack subscriber who never acks will never get messages. 
Fix is during reject - reduce non ack message count of the channel .
Fixing https://wso2.org/jira/browse/MB-1143
> added changes to reduce non ack message count during message reject.

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagePurgeRule.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/AMQPLocalSubscription.java
As per jira : https://wso2.org/jira/browse/MB-948
If a queue is purged while its messages are in the middle of the delivery logic, a warning like following will be printed and the message will not be delivered, since it had arrived before the purge event.
WARN {org.wso2.andes.kernel.MessagePurgeRule} -  Message was sent at 1437116635408 before last purge event at 1437116635856. Therefore, it will not be sent. id= 37785602728394752
> Enabling Purge Delivery Rule

- modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
-  Management console message browsing property name messageBatchSizeForBrowserSubscriptions
changed to messageBrowsePageSize with implementation changes made to browsing
> config reading changed in AndesConfiguration

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/ConcurrentTrackingList.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/LocalSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageData.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageFlusher.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/OnflightMessageTracker.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/AckHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundAndesChannelEvent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundSubscriptionEvent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTLocalSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/subscription/SubscriptionImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/AMQPLocalSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java
1. removing sending tracker from onflight message tracker
2. removing un-ack message counting from Onflight message tracker.
3. Fix OOM issue of topics - when there are slow topic subscribers broker goes OOM as Queue entries are accumulated in transport level. Fix is to flow control topic messages. Messages to slow subscribers who are stuck at the moment will be lost.
> Re-arranging onflight message tracker

- modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/server/Server.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/AndesConfigurationManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/modules/JKSStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/qpid/ServerConfiguration.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/util/MetaProperties.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/Broker.java
This is with reference to jiras : 
https://wso2.org/jira/browse/MB-924 
https://wso2.org/jira/browse/MB-1160
At server startup, AndesConfigurationManager will scan for any encrypted properties within broker.xml and add their decrypted values to a static hashmap. Whenever a property is read, this map will be cross referenced to find the decrypted value. This approach is used because cipher tool is dependent on using an AXIOM xml parser. 
A common data structure is used to parse AMQP / MQTT JKS store configurations into the server. Refer JKSStore.java
AMQP SSL configurations are now parsed through AndesConfiguration instead of ServerConfiguration (QPID code.)
This is dependent on : https://github.com/wso2/carbon-business-messaging/pull/100
> Initial commit for broker.xml to support ciphertool and to move amqp/mqtt ssl configurations into broker.xml

- modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/AndesConfigurationManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/util/TopicMessageDeliveryStrategy.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContext.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlledQueueMessageDeliveryImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageDeliveryStrategy.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageFlusher.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/NoLossBurstTopicMessageDeliveryImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/SlowestSubscriberTopicMessageDeliveryImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/TopicMessageDeliveryStrategy.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/AMQChannel.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/ack/LimitedSizeQueueEntryHolder.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/ack/UnacknowledgedMessageMapImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/queue/QueueEntry.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/queue/QueueEntryImpl.java
- modules/andes-core/broker/src/test/java/org/wso2/andes/server/ExtractResendAndRequeueTest.java
- modules/andes-core/broker/src/test/java/org/wso2/andes/server/exchange/AbstractHeadersExchangeTestBase.java
- modules/andes-core/broker/src/test/java/org/wso2/andes/server/queue/MockQueueEntry.java
We brought 3 TopicMessage delivery strategies
<topicMessageDeliveryStrategy>
<strategyName>DISCARD_NONE </strategyName>
<deliveryTimeout>60</deliveryTimeout>
</topicMessageDeliveryStrategy>	
Default strategy is "DISCARD_NONE". 
Also added strategy pattern for message delivery strategies. Now when a new way of message delivery is required MessageDeliveryStrategy interface.
> Added new delivery strategies for topic message delivey

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/NoLossBurstTopicMessageDeliveryImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/OnflightMessageTracker.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorker.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTLocalSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/AMQPLocalSubscription.java
1. Minor code changes 
2. Added flow control for topic subscribers. Now in NoLossBurstTopicMessageDeliveryImpl message delivery strategy, if non of the subscribers can accept messages we do not deliver any of the messages in the message lot after that has detected. When buffer is flushed again, those messages will be tried again.
> Code cleanups

- modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/messaging/spi/impl/ProtocolProcessor.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTAuthorizationSubject.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/utils/MQTTUtils.java
MQTT publish or subscribe methods does not allow to provide
authentication information. Therefore keeps MQTT client
information in memory when connecting and use those information
when publishing or subscribing to do tenant validation.
These details are removed when the client is disconnected.
Modified changes done by @akalankapagoda, to send a sub ack if at
least one subscription is allowed for the user.
> Add tenant authentication for MQTT.

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlledQueueMessageDeliveryImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageFlusher.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/NoLossBurstTopicMessageDeliveryImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/OnflightMessageTracker.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/SlowestSubscriberTopicMessageDeliveryImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DeliveryEventHandler.java
The reason was decrementing scheduled delivery count before sending the message to subscription. After moving the decrement call to finally block in the DeliveryEventHandler#onEvent we did not observe the null pointer exception.
> Scheduled delivery count race condition fix

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesMessageMetadata.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
Addresses the jira https://wso2.org/jira/browse/MB-1184.
The issue was due to the fact that the message content length was not being updated when metadata is cloned by the MessagePreProcessor. Resolving this issue solved the problem of ContentChunkHandler going out of memory.
Also message metadata in the cache having isTopic = true prevented messages from being delivered to durable subscriptions.
Please merge https://github.com/wso2/product-mb/pull/161 to enable the test case
> Fixed durable topic messages not being restored from DLC issue

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/LocalSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/AMQPLocalSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java
With shared topic subscription feature enabled there were issues with creating and removing subscriptions. Now we follow following model with this commit. 
create subscription  - first sub: 
localsubscription map has nothing. But cluster map might have more than one active entries or one inactive entry. 
>> check cluster subs. if there is at least one active entry, just create another and notify create. if there is one inactive entry, whatever it is, take it and make it active, and notify. 
subsequent subs:
localsubscription map has entries.  cluster map might have more than one active entries
>> just create new entries in DB and notify. 
close subscription   - when there are more than one
localsubscription map has more than one entry. cluster map has more than one entry
>>delete the …
> Fix durable topic subscriptions

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java
Fix issues occured when removing non-durable subscriptions.
This PR is related to https://github.com/wso2/andes/pull/286 PR. Following subscription removing senarios will be covered with these fixes.
1. Remove non-durable subscriptions during startup and shuting down the server for it's node id.
2. Remove non-durable subscriptions when member removed for removed node id.
jira - https://wso2.org/jira/browse/MB-1172
> [MB-1172] Fix issues in remove non durable subscriptions

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeleteSafeZoneCalc.java
safe zone calculation should never stop if the node is live. 
If the network is gone for the node, on exceptions it should backoff, and retry if when the network came back. 
Safe zone calculation is done only by coordinator node. If the coordination was removed from cluster, other nodes will detect member left, a new coordinator will be elected and that coordinator will remove the removed node's entry from safe zone calc. Otherwise safe zone will not proceed and slots will not removed from cluster.
> fix safe zone calculation logic. 

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesRecoveryTask.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/queue/DLCQueueUtils.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java
Durable topic has been saved to DB with topic.carbon:subID signature. This causes problems with syncing it with in-memory maps as in maps we keep subscriptions w:r:t topic name. Modified to save durable topic subscriptions in DB as
topic.[topic name] (i.e topic.myTopic).
Also when syncing for durable topic subscriptions we have "hasExternalSubscriptions" attribute. This can be updated but not synced to maps. Thus when syncing for durable topic subscriptions we always DELETE the existing subscription and add whatever in DB.
> added fix to syncing durable topic subscriptions.

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/NoLossBurstTopicMessageDeliveryImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/SlowestSubscriberTopicMessageDeliveryImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/AckHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundDeleteMessagesEvent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundTransactionEvent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingMessageStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/CQLBasedMessageStoreImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/cassandra/HectorBasedMessageStoreImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java
This PR separates the method deleteMessages in MessagingEngine as deleteMessages and moveToDLC since having a single method to perform both tasks was confusing.
Addresses the jira https://wso2.org/jira/browse/MB-1186
Please merge https://github.com/wso2/product-mb/pull/163 along with this or else PurgeMessagesTestCase might fail. Even though there is no direct connection, the test case started failing after this change.
> Separated method deleteMessages in MessagingEngine into two

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageData.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/OnflightMessageTracker.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/AckHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/StateEventHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/OrphanedSlotHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorker.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorkerManager.java
Previouly we use numberOfScheduledDeliveries and
channelToNumOfDeliveries to check if a message can be deleted from
database. In this commit the pendingAckCount is used to track if
all the acks are received. This count is incremented when the
message is given to the outbound disruptor and decremented when an
ack is received.
> Change allAcksReceived check

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/OnflightMessageTracker.java
Addresses the jira https://wso2.org/jira/browse/MB-1202
The problem was caused by the message delivery count being decremented when a rejection is received. Was resolved by only reducing the 'pendingAckCount' which keeps track on the non-acknowledged message count.
> Messages not being moved into DLC issue fixed

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/AckHandler.java
- AckHandler clear event when ack received. Therefore StateEventHandler not getting ACKNOWLEDGEMENT_EVENT. This is cause slot not getting deleted. Therefore event.clear() statement removed from AckHandler because event is finally getting clear in StateEventHandler.
> Slot not deleting issue fixed.

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MaximumNumOfDeliveryRule.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
Addresses https://wso2.org/jira/browse/MB-1208
The issue was caused by the usage of the method 'Arrays.asList(array)'
The list returned is not java.util.ArrayList, but a private static class defined inside java.util.Arrays which does not support the remove method.
Please merge https://github.com/wso2/product-mb/pull/174 to enable the test cases
> DLC restoring using cached content issue fix

- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQSession.java
- Previous change was to return false when publisher flow control while failover. This was change to throw an JMS exception to propage it to caller.
- Minor change to log messages in SubscriptionStore.
> checkFlowControl() modification in andes-client

- modules/andes-core/broker/src/main/java/org/wso2/andes/store/cache/AndesMessageCache.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/cache/DisabledMessageCacheImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/cache/GuavaBasedMessageCacheImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java
Addresses the jira https://wso2.org/jira/browse/MB-1217
When messages were moved to DLC, they were removed from the cache.
> [MB-1217] Removed messages that are moved to DLC from cache

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/AMQPUtils.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/QpidAndesBridge.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/cache/GuavaBasedMessageCacheImpl.java
Addresses the jira https://wso2.org/jira/browse/MB-1220
Please merge https://github.com/wso2/product-mb/pull/184 to enable the ViewMessageContent test case
> [MB-1220] Large message retrieval from cache indexOutOfBoundsException fixed

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
- Existing tracing order is ACK_PUBLISHED_TO_DISRUPTOR -> ACK_RECEIVED_FROM_PROTOCOL. This changed to ACK_RECEIVED_FROM_PROTOCOL -> ACK_PUBLISHED_TO_DISRUPTOR.
> Tracing message location flip

- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
JIRA - https://wso2.org/jira/browse/MB-1234
We were retrieving assigned slots from database for checking overlapped slots. In previous implementation, we queried slot records and created list of slot objects using those records to return. But when creating list of slot objects, we did not set the slot slate of those new slots to ASSIGNED state. So those slots were in CREATED state. When an overlapped slot was found in the returned list of slots, we update that slot state to OVERLAPPED. In that case, warning will be displayed saying invalid state transition from CREATE to OVERLAPPED.
Fix is to set slot state to ASSIGNED when creating list of slots. Therefore when updating state to OVERLAPPED, it won't be an invalid state transition.
> Fix for slot invalid state transition occurs when overlapping slots

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundDeleteMessagesEvent.java
Addresses the jira https://wso2.org/jira/browse/MB-1254
The issue was due to an empty check on non-initialized list 'deliverableAndesMetadataList' in the class InboundDeleteMessageEvent.
> Fixed NPE when deleting message from DLC

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/QpidAndesBridge.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DeliverableAndesMetadata.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageStatus.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/LocalSubscription.java
- Publisher and subscriber create and close connection for each message and did some test rounds. This was cause to duplicate and loss messages in new delivery model. It has fixed with changes in this commit.
> Message duplicate/loss issue fixed in pub/sub close.

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/QpidAndesBridge.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DeliverableAndesMetadata.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageStatus.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DeliveryEventHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/tools/utils/MessageTracer.java
- duplicate messages received when subscriber create and close connection per message. It has fixed with this changes.
- new tracing inforamation added to Message Tracer to identify message requeue to buffer and message discarded when subscriber close
- Message status check changed to avoid sent to all to sent to all and slot return to sent to all
> message duplicate issue fixed in subscriber create and close connection per message

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DeliverableAndesMetadata.java
- NullPointerException occurred whilee subscriber create and close connection per message. This was cause to loss messages. At any given moment subscriber connection could be close. At that time we remove channelInformation. So in delivery path, NullPointerException could occur while messages sending. This has handle with null check until proper model introduce.
- Public Jira https://wso2.org/jira/browse/MB-1300
> [MB-1300] issue fixed.

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageFlusher.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorker.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorkerManager.java
Initialize the message flusher when slot delivery worker is given a
destination to deliver messages.
https://wso2.org/jira/browse/MB-1314
> [MB-1314] NullPointerException when subscriber closes connection without consuming messages

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/AMQPUtils.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AMQPDeliveryRule.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/ChannelMessageStatus.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/CommonDeliveryRule.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DeliverableAndesMetadata.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/HasInterestRuleAMQP.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MaximumNumOfDeliveryRuleAMQP.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageExpiredRule.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageFlusher.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagePurgeRule.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageStatus.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/NoLocalRuleAMQP.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/ProtocolDeliveryFailureException.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/ProtocolDeliveryRulesFailureException.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/ProtocolMessage.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/ConcurrentContentReadTaskBatchProcessor.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/ContentCacheCreator.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DeliveryEventData.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DeliveryEventHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DisruptorBasedFlusher.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/Slot.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTLocalSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/message/AMQMessage.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/subscription/SubscriptionImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/AMQPLocalSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/LocalSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/OutboundSubscription.java
Message status - Removed SENT_TO_ALL status
Channel Message Status  - Removed SENT, RESENT status
Moved purge rule and message expiry rules to the kernel. Now we have two types of delivery rules
AMQPDeliveryRule - AMQP protocol specific
CommonDeliveryRule - kernel level delivery rule
Now state updates are not done inside outbound disruptor. If a send failure happens we detect two types of exceptions and operate on them. 
ProtocolDeliveryFailureException - protocol could not publish - requeue message if durable
ProtocolDeliveryRulesFailureException - protocol level delivery rules failed - send message to DLC if durable
> updated message delivery model.

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/NoLossBurstTopicMessageDeliveryImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/SlowestSubscriberTopicMessageDeliveryImpl.java
"findNextSubscriptionToSent" can give the same subscription to deliver
in some situation (when subscription iterator is swapped). This
behaviour is not acceptable for topics. Therefore call to
findNextSubscriptionToSent was replaced by a simple "for loop" in
topic delivery strategies.
> findNextSubscriptionToSent is not used to pick subscription for topics

- modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/messaging/spi/impl/ProtocolProcessor.java
- modules/andes-core/broker/src/main/java/org/dna/mqtt/wso2/AndesMQTTBridge.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTAuthorizationSubject.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTopicManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/connectors/InMemoryConnector.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/connectors/MQTTConnector.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/connectors/PersistenceStoreConnector.java
Currently "admin" user has hard coded as queue owner due to permission issues occured when purge/remove queues. with this fix queue owner is taken from carbon user of subscription.
jira - https://wso2.org/jira/browse/MB-1357
> [MB-1357] Remove hard coded admin in MQTT PersistenceStoreConnector.

- modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
Addresses the issue reported at https://wso2.org/jira/browse/MB-1393
The issue was caused due to the following factors:
1. When browsing a queue we select messages from the last assigned slot message id rather than from 0 .
2. The last assigned slot message id is retrieved from the slotIdMap which will only be initialized when subscribers are connected (Slots are assigned only when subscribers are present).
3. Therefore, when we create a queue and publish messages(without subscribing) and try to browse the queue, the slotIdmap is not initialized and an NPE occurs.
> Fixed UI test failures

- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java
Fix for storing empty payloaded retain messages in mb.
https://wso2.org/jira/browse/MB-1382
> [MB-1382] Fix issue in remove retain message

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/queue/DLCQueueUtils.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingMessageStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java
- modules/andes-core/management/common/src/main/java/org/wso2/andes/management/common/mbeans/QueueManagementInformation.java
Addresses the issue reported at https://wso2.org/jira/browse/MB-1268
The issue was caused by a large number of queries being executed on the database. The Method to retrieve all queues was implemented as follows:
1. Get all the queue names from the AMQPConstructStore
2. For each name, get the number of messages in the database from the metadata table
Therefore, a database call was made for each query in the construct store. The solution to the issue was to get the message count in the metadata table grouped by each queue_id by a single db call. This way, the operation to retrieve all queues is converted to a single operation rather than a number of operations retrieving each queue.
Please merge https://github.com/wso2/carbon-business-messaging/pull/171 and …
> [MB-1268] Implemented message count retrieval for all queues

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
log static variable still not initialized when it's called in SlotManagerClusterMode class. this was the cause for java.lang.NoClassDefFoundError: Could not initialize class org.wso2.andes.kernel.slot.SlotManagerClusterMode.
> Fix for error occured when clustering enabled

- modules/andes-core/broker/src/main/java/org/wso2/andes/server/AMQChannel.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/ack/UnacknowledgedMessageMapImpl.java
- modules/andes-core/broker/src/test/java/org/wso2/andes/server/ExtractResendAndRequeueTest.java
Fixing - https://wso2.org/jira/browse/MB-1419
Use the LimitedSizeQueueEntryHolder only for topic messages and restrict andes client to allow only one consumer per session.
This is because although QPID is designed so that there can be many consumers per session, Andes is designed so that session and consumer is a one-to-one mapping.
> [MB-1419] Use limited max unacked messages only for topic and restrict client session to have only one consumer

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/TopicParserUtil.java
Fix issue when subscribed with "+/+/+" the subscriber receives
retained messages from two level topics (e.g. testx/testy). Topic
matching logic was modified after looking at a fix done in the
forked project mqtt-mouette.
https://wso2.org/jira/browse/MB-1404
> [MB-1404] [MQTT] When subscribed with "+/+/+" the subscriber receives retained messages from multilevel topics

- modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/messaging/spi/impl/ProtocolProcessor.java
Remove MQTTAuthorizationSubject after informing subscription disconnection to bridge.
https://wso2.org/jira/browse/MB-1445
> [MB-1445] [MQTT] Cannot subscribe again using the same client-id when subscription is killed without disconnecting 

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DeliverableAndesMetadata.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/SubscriptionAlreadyClosedException.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DeliveryEventHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/subscription/SubscriptionImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/AMQPLocalSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/LocalSubscription.java
This class handles what happens when
1. scheduled subscriber is closed
2. actual protocol delivery error occurred
3. when a message is stale 
If message is scheduled to x num of topic subscribers and in the middle of delivery if one subscriber vanished ACK is evaluated on rest of x-1 subscribers and message deletion is evaluated. 
etc.
> Refactored Delivery Event Handler

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextInformationManager.java
Addresses the issue reported at https://wso2.org/jira/browse/MB-1245.
If the user becomes unable to unsubscribe once, he will never be able to unsubscribe since the queue is deleted prior to unsubscribing (the existence of the queue is checked at an early stage of unsubscribing). This PR does not solve the issue completely, but minimizes the issue to some extent by deleting the queue only after unsubscribing, therefore becoming able to attempt once again.
> [MB-1245] DurableTopicsSubscribers are not getting unsubscribed

- modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/QueueDeclareHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/protocol/AMQProtocolEngine.java
1. Previously, always "access refused" error was propagated. 
2. Error when creating queues were not propagated.
> Properly propergate queue creation and binding creation errors to andes client

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesMessageMetadata.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTLocalSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTopicManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTopics.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/connectors/InMemoryConnector.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/connectors/MQTTConnector.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/connectors/PersistenceStoreConnector.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/utils/MQTTUtils.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/AMQPLocalSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/BasicSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/LocalSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/OutboundSubscription.java
This pull fixes the following issues.
https://wso2.org/jira/browse/MB-1472
https://wso2.org/jira/browse/MB-1471
https://wso2.org/jira/browse/MB-1468
https://wso2.org/jira/browse/MB-1425
https://wso2.org/jira/browse/MB-1334
https://wso2.org/jira/browse/MB-1423
MQTT subscription handling is changed so that when a client is connected to two different topics, Andes will create two subscriptions, one per each topic, manipulating the subscription ID.
Changed the storage queue name for clean session = false subscribers to a combination of clienId + topic, instead of just client Id.
> Fix mqtt clean session = false delivery path and resolve delivery when a subscriber changes the subscribed topic.

- modules/andes-core/broker/src/main/java/org/wso2/andes/server/binding/BindingFactory.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/exchange/topic/TopicExchangeResult.java
Fix for : https://wso2.org/jira/browse/MB-1389
When a durable subscription is added with a selector, and then changed to exclude that selector, the code goes through https://github.com/wso2/andes/blob/master/modules/andes-core/broker/src/main/java/org/wso2/andes/server/binding/BindingFactory.java#L128, which causes the an unbind call to the registry, removing the registry entry for that subscription.
Problem was that, the entry addition was happening before the unbind. Without the registry subscription entry at "_system/governance/event/topics/topic1/jms.subscriptions/", the topic browse page hides the subscription.
> fix_jira_1389

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/ClusterSubscriptionBitMapHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/ClusterSubscriptionHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java
This pull fixes the following issues.
https://wso2.org/jira/browse/MB-1444
https://wso2.org/jira/browse/MB-1446
Update durable topics with wildcards from bitmap handler when loaded from db.
> Update durable subscriptions properly when loaded from db

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DeliverableAndesMetadata.java
This fix is related to : https://wso2.org/jira/browse/MB-1449.
If a delivery failure exception happened during message delivery (even a null pointer), message will be re-tried a finite number of times (see configuration MaximumNumberOfDeliveries) for a given subscriber. Then it will be moved to DLC.
> [MB-1449] fix issue of replacing channelInfo object when rescheduled.

- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/connectors/PersistenceStoreConnector.java
Avoid deleting queue info when an mqtt client is disconnecting. 
Durable subscribers will need to keep it and non-durable subscribers do not have it.
> Avoid deleting queue info when an mqtt client is disconnecting. 

- modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/SubscriptionManagementInformationMBean.java
Storage queue name was used (instead of target queue) to lookup
pending messages for a subscriber.
https://wso2.org/jira/browse/MB-1499
> [MB-1499] tmp entries observed in MB_QUEUE_MAPPING table

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextInformationManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/ClusterCoordinationHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java
Addresses the issue reported at https://wso2.org/jira/browse/MB-1245.
The issue occurred when trying to unsubscribe durable subscriptions after restarting the whole cluster. The root cause for the issue was that the subscriptions were identified from local subscription maps and the local subscription maps were empty after restarting nodes.
The issue was solved by deleting all cluster subscriptions from the cluster subscription masp regardless of its presence in the local subscription map.
> [MB-1245] Fixed issue in unsubscribing durable subscriptions

- modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/messaging/spi/impl/ProtocolProcessor.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTLocalSubscription.java
Fix for https://wso2.org/jira/browse/MB-1515.
Change MQTT storage queue name to behave the same as AMQP when it is not durable.
Remove processing of last will messages since it is not yet supported.
> Change MQTT storage queue name and restrict will message

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/QpidAndesBridge.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/QueueDeclareHandler.java
Addresses the issue reported at https://wso2.org/jira/browse/MB-1497.
The issue is caused by the fact that the queue creation is case insensitive and thus subscription ids with different cases are considered as the same. The ideal solution would be to make the queue creation case sensitive. But due to https://wso2.org/jira/browse/CARBON-15535, queue creation cannot be made case sensitive. Thus prohibited queue creation in different cases. This should be changed with the fix for https://wso2.org/jira/browse/CARBON-15535.
> [MB-1497] Made queue creation case insensitive

- modules/andes-core/client/src/main/java/org/wso2/andes/client/protocol/AMQProtocolHandler.java
When the client is started with "amqj.protocol.logging.level=1" system property, all received packets to the client will be logged. But the sent packets cannot be seen as it is in "debug" level. 
Therefore changing it to "info" log.
> Modified debug log to info log in AMQProtocolHandler for client jar.

- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTLocalSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTopicManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/connectors/InMemoryConnector.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/connectors/MQTTConnector.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/connectors/PersistenceStoreConnector.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/utils/MQTTUtils.java
In MQTT subscribers, it is consider as durable where clean session is false and qos is greater than 0. Use this logic in locations where MQTT durability is in required.
> Consider durability in mqtt with regards to qos and clean session

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/OrphanedSlotHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/BasicSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java
Scenarios:
in a cluster: 
1) 2 shared subscribers exists in same node and one disconnects 
2) OrphanedSlotHandler will return those slots to coordinator
3) These slots will be given to another node (sometimes) this leads to lots of errors 
(in ackhandler and/or delivery path) in both nodes.
Fix is was to use proper queues/destinations etc.
> [Shared Subscriptions] Fixing a problem in how slots are reassigned during client disconnect

- modules/andes-core/broker/src/main/java/org/wso2/andes/server/NameValidationUtils.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/binding/BindingFactory.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/queue/AMQQueueFactory.java
Changes related to invalid queue names/topic names/subscription ids
MB-1386 : Queue/Topic names should be trimmed before saving
MB-1391 : If a message is published from UI to a topic with a name which has a space in-between the message is not routed to the subscribers
MB-1427 : Prevent topic creation which has two full stops subsequently e.g - Sports..
MB-1455 : Queue names which has the " / " is not shown in UI
MB-1467 : Inconsistent behavior in super tenant and tenant space when trying to subscribe from JMS client
MB-1470 : "Cannot access the config registry" error message is displayed when trying to create a topic with *, # characters 
This fix includes validations of queue/topic names, when creating queues/topics from both UI and clients.
As said in the AMQP specification, this PR …
> MB-1386, MB-1391, MB-1427, MB-1455, MB-1467, MB-1470

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/AMQPUtils.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/OrphanedSlotHandler.java
This is done to avoid a warning printed in the logs. Refer MB-1529
https://wso2.org/jira/browse/MB-1529
> Tracked subscriptions are only removed when deleting

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/QpidAndesBridge.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/QueueDeclareHandler.java
Addressed the issue https://wso2.org/jira/browse/MB-1497
The issue was originally fixed by https://github.com/wso2/andes/pull/434. But it was reverted since adding shared subscriptions was prohibited by it. 
This PR makes a slight change into that by changing:
catch (AMQException e) {
queueRegistry.unregisterQueue(queueName);
throw body.getChannelException(AMQConstant.INTERNAL_ERROR, e.getMessage());
}
to 
catch (AMQException e) {
throw body.getChannelException(AMQConstant.INTERNAL_ERROR, e.getMessage());
}
since the previous PR had unregistered the queue created by the other shared subscription.
> Blocked queue creation from different cases

- modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/messaging/spi/impl/ProtocolProcessor.java
Previously the subscription was accepted even though authorization
fails when MQTT version is not equal to 3.1.1
https://wso2.org/jira/browse/MB-1378
> [MB-1378] [MQTT] Tenants can create topics without tenant domain as the prefix

- modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQSession.java
Prevent publisher creating topics without a subscriber
This fix addresses issue reported at:
https://wso2.org/jira/browse/MB-1535
> MB-1535: Should not allow publishers to create topics

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/AMQPUtils.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextInformationManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundQueueEvent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java
Addresses the issue reported at https://wso2.org/jira/browse/MB-1533
The issue occurred since the the check for active subscriptions upon a queue delete request was only done for queues but not for topics.
> [MB-1533] Added check to find active subscribers when deleting durabe subscriptions

- modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/messaging/spi/impl/ProtocolProcessor.java
- modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/server/ServerChannel.java
- modules/andes-core/broker/src/main/java/org/dna/mqtt/moquette/server/netty/NettyChannel.java
This pull fixes the issue https://wso2.org/jira/browse/MB-1548.
When a new client joins with a client id that is the same as an already connected client, according to MQTT spec, the existing client should be disconnected and the new client should be connected.
http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc398718032
"If the ClientId represents a Client already connected to the Server then the Server MUST disconnect the existing Client [MQTT-3.1.4-2]."
> MQTT close previous connection if a new client joined with the same client id

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/AMQPUtils.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AMQPConstructStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesChannel.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextInformationManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/connectors/PersistenceStoreConnector.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/utils/MQTTUtils.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/AMQChannel.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/virtualhost/VirtualHostConfigSynchronizer.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingMessageStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQSession.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/BasicMessageProducer.java
Applied the changes in #377 with fixes for deleting the queue mapping entries from in-memory maps upon the receipt of a cluster queue delete notification.
Also, the Hashmap for storing queue mapping was removed and a guava cache was used in place.
In addition, https://github.com/wso2/andes/pull/418 ([MB-1433] Create queue when publishing) was reverted and a message published to a non-existing queue was dropped.
> Publish to a non existing queue

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/AMQPUtils.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlledQueueMessageDeliveryImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageFlusher.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/NoLossBurstTopicMessageDeliveryImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/SlowestSubscriberTopicMessageDeliveryImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/MessagePreProcessor.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTLocalSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/AMQPLocalSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/LocalSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/OutboundSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionStore.java
This is done to implement message selectors properly. We need to filter the subscriptions based on selector before we deliver. 
Fixing https://wso2.org/jira/browse/MB-1600
> Moved HasInterest AMQP Delivery rule to a common rule. 

- modules/andes-core/client/src/main/java/org/wso2/andes/client/BasicMessageConsumer.java
JMS transactions sometimes resulted in loss of message order. The reason was that multiple messages were being published on the same exact timestamp, and the below condition could not handle it. 
Added a new factor to the condition as a fix.
> [MB-1482] Fix condition to distinguish redeliveries

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/CommonDeliveryRule.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlledQueueMessageDeliveryImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageDeliveryInfo.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageDeliveryStrategy.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageExpiredRule.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageFlusher.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagePurgeRule.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/NoLossBurstTopicMessageDeliveryImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/SlowestSubscriberTopicMessageDeliveryImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DeliveryEventHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorker.java
Move MessageDeliveryInfo class to a separate file instead of an inner class.
Then forward MessageDeliveryInfo objects from SlotDeliveryWorker to MessageFlusher to delivery messages instead of sending parameters separately and selecting the MessageDeliveryInfo class from within MessageFlusher.
> Separate message delivery info for destination type

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/NoLossBurstTopicMessageDeliveryImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/SlowestSubscriberTopicMessageDeliveryImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionProcessorBuilder.java
Modify delivery strategies to retrieve subscriptions using the message delivery info destination and retrieve the subscriptions once per buffer. Then use queue subscription store to store local topic subscriptions. This will avoid retrieving local topic subscriptions from bitmap subscription implementation which provides erroneous data intermittently.
> Use queue subscription store for local topic subscriptions and retrieve local subscriptions once per buffer

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/AMQPUtils.java
Adding changes in https://github.com/wso2/andes/pull/499 in a new pull request with minor changes.
"We were checking if a destination contains ".*" or ".#" to identiify
a wildcard destination in AMQPUtils#isWildCardDestination.
Removed "." character infront of wild card character to identify
wildcard prefixed destinations (such as *.SriLanka)
https://wso2.org/jira/browse/MB-1552"
> Fixing AMQP prefixed wildcards according to spec.

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/Slot.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeletionExecutor.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingMessageStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java
Additional check added for slot deletion executor to check whether there are messages in database before trying to delete a slot.
There is a scenario where a slot scheduled to delete, becoming overlapped and then assigned to a
node after some time. Then coordinator will allow to delete the slot while overlapped slot messages
are in delivery path (race condition). To avoid this a DB message count check is added before querying
coordinator for a slot deletion. This guarantees that slots are not deleted until messages in overlapped
slots are successfully delivered.
JIRA: https://wso2.org/jira/browse/MB-1612
> Fix for fresh slot deleted before overlapped slot is delivered

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeletionExecutor.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorker.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotMessageCounter.java
1. Revert node-wise safe zone to slots that are still filling up to avoid deleting slots before completion.
2. Fix SlotDeletionTask while loop and adding error logs for context.
> [MB-1611] and fixing an issue at the SlotDeletionExecutor

- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
The most desired option is to enclose the connection/prepared statements between Try-with-Resources. http://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html
This should be reflected in all database operations. Hence it will be tabled for future
> Fixing the connection leak in prepared statements 

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/compression/LZ4CompressionHelper.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/ContentDecompressionHandler.java
Fix of decompress using lz4, when the compressed message size is greater than the original message size
> [MB-1619] Fix of applying lz4

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/AMQPLocalSubscription.java
Internal memory map 'storedMessageCache' is accessed concurrently by two threads. Having a HashMap would cause a commonly know racing condition in the long run [1]. Hence the map will be synchronized.  
[1] http://mailinator.blogspot.nl/2009/06/beautiful-race-condition.html
> Synchronize memory map which is being accessed concurrently   

- modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundTransactionEvent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/MessagePreProcessor.java
Transactional publisher commit doesn't return when there are no subscribers for the same topic.
Fixed by removing inbound event clear method from message preprocessor and adding a timeout for the settable future get method.
JIRA: https://wso2.org/jira/browse/MB-1629
> Fix transactional publisher commit not returning issue

- modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQSession.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/BasicMessageConsumer.java
This pull fixes the issue - https://wso2.org/jira/browse/MB-1640.
> In Andes client, reject available messages before sending a close event

- modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQConnectionDelegate_8_0.java
jira : https://wso2.org/jira/browse/MB-1650
> Fixed MB-1650 and make the warning log of keystore loading from class path only when ssl is enabled

- modules/andes-core/client/src/main/java/org/wso2/andes/client/protocol/HeartbeatDiagnostics.java
Avoid concurrent access on Heartbeat Diagnostics to fix ArrayIndexOutofBoundsException.
> Fixing MB-1635. 

- modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQConnectionDelegate_8_0.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/pool/ReferenceCountingClientExecutorService.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/protocol/AMQProtocolHandler.java
- modules/andes-core/common/src/main/java/org/wso2/andes/pool/Job.java
- modules/andes-core/common/src/main/java/org/wso2/andes/pool/ReferenceCountingExecutorService.java
- modules/andes-core/common/src/main/java/org/wso2/andes/pool/ReferenceCountingService.java
In reference to https://wso2.org/jira/browse/MB-1659, Commit will fix the issue which has a thread leak in SocketConnectorIoProcessor. The PR also fixes the issue of requiring Guava dependency for client side reference counting.
> Fix for https://wso2.org/jira/browse/MB-1659 and introducing a separate class for client reference counting 

- modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQConnectionDelegate_8_0.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/pool/ReferenceCountingClientExecutorService.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/protocol/AMQProtocolHandler.java
- modules/andes-core/common/src/main/java/org/wso2/andes/pool/Job.java
- modules/andes-core/common/src/main/java/org/wso2/andes/pool/ReferenceCountingExecutorService.java
- modules/andes-core/common/src/main/java/org/wso2/andes/pool/ReferenceCountingService.java
Fixes thread leak described in MB-1659, adds a separate reference counting thread-pool for andes client
> Fixes MB-1659, merged changes related to naming reference counting thread pool

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/QpidAndesBridge.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/AMQChannel.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/ExtractResendAndRequeue.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/BasicRecoverMethodHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/BasicRecoverSyncMethodHandler.java
This is done to avoid messages being redelivered before Recover-OK
is sent to the client.
>  Messages requed after sending Recover-OK

- modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/ConnectionCloseMethodHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/protocol/AMQProtocolEngine.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/protocol/AMQProtocolSession.java
- modules/andes-core/common/src/main/java/org/wso2/andes/pool/ReferenceCountingExecutorService.java
- modules/andes-core/common/src/main/java/org/wso2/andes/protocol/AMQProtocolWriter.java
Add a synchronous method to write the Close-OK frame to client since
in session.closeSession() we shutdown the pool job if no consumers
are left.
> Fix pool job closing issue before sending Close-OK

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesMessageMetadata.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesUtils.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/message/MessageMetaData.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/store/MessageMetaDataType.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/virtualhost/VirtualHostConfigRecoveryHandler.java
Use AMQP version 0_91 by default instead of 0_80 for published messages for resolving the correct subscription store.
The TODO's added here should get rectified when re-structuring the message meta data due for c5 which ultimately removes the hard coded version.
> Use AMQP 0_91 version instead of 0_80 by default for published messages

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/resource/manager/AndesResourceManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/resource/manager/DefaultResourceHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/resource/manager/ResourceHandler.java
In MB based on C4, all resources and operations on queues, topics, subscriptions and messages were exposed through an MBean JMX platform which came along with Qpid. The UI of MB was designed in a way that the JSP pages will first call a webservice through service stubs and then the webservice backend will use a JMX client which talks to the MBean server. 
Following is the architecture diagram on how it worked : 
So whenever we want to handle MB resources, we always have to use the Qpid JMX MBeans implementation.
For MB based on C5, the plan is to use OSGi services by having a manager class within andes core which provides services based on the type of protocol(example : amqp,mqtt) and destination type(example: queue,topic). As of now, we are moving the transport based implementation out …
> Added initial code for resource manager feature.

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesRecoveryTask.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingAndesContextStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/subscription/SubscriptionEngine.java
Addresses the issue reported at https://wso2.org/jira/browse/MB-1682
The solution for this was to modify the db sync task so that the database get first updated with the entries in the local subscriptions map, then update the cluster map according to what's in the database. This will prioritize the local subscription map over the db thus the cluster subscriptions map will be consistent with the local subscriptions map.
> [MB-1682] Fixed issue of subscriptions being removed when nodes merge after split brain

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/HazelcastLifecycleListener.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/HazelcastClusterAgent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/AndesMembershipListener.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/error/detection/DisabledNetworkPartitionDetector.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/error/detection/HazelcastBasedNetworkPartitionDetector.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/error/detection/NetworkPartitionDetector.java
Instead of getting the number of members through hazelcast agent, the number of member will be taken from the membershipEvent that occurs on memberAdded and memberRemoved.
> [MB-1694] Modified partition listener to get the number of cluster members through membership event fired by memberAdded and memberRemoved method.

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorker.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorkerManager.java
Reverts wso2/andes#603 due to deadlock issue[1] introduced by changes in SlotDeliveryWorker.setRunning().
This will reopens the MB-1671 issue fixed by wso2/andes#603.
[1] https://wso2.org/jira/browse/MB-1696
[2] https://wso2.org/jira/browse/MB-1671
> Revert "Wait for SlotDeliveryWorker to stop it's running thread before completing stop delivery"

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesSubscriptionManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotCoordinatorCluster.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeletionExecutor.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeliveryWorker.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/ClusterAgent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/HazelcastClusterAgent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/error/detection/DisabledNetworkPartitionDetector.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/error/detection/HazelcastBasedNetworkPartitionDetector.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/error/detection/NetworkPartitionDetector.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/protocol/AMQProtocolEngine.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/protocol/AMQProtocolSession.java
- Make globalErrorBasedFlowControlEnabled variable volatile
- Throw AMQException instead of a Runtime exception when channel ID
is not found. This done to continue network partition listener
processing
- Process networkn partition listeners in order. A pririority level
is introduced for each network partition listener. Additionally a
network flag partition flag was introduced on AndesSubscription
manager to block all subscription additions after a network
partition was detected.
> Fix MB-1678

- modules/andes-core/client/src/main/java/org/wso2/andes/client/BasicMessageProducer_0_8.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/CustomJMSXProperty.java
This PR contains a feature which adds a routing key as a JMS message property for messages. 
To activate this feature, set any value to "AndesSetRoutingKey" system property from publisher client side.
JIRA - https://wso2.org/jira/browse/MB-1699
> [MB-1699] Added custom property for message to store original destination.

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesUtils.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/CoordinationConfigurableClusterAgent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/CoordinationConstants.java
As per spec special characters including pipe "|" has not allowed in topic names.
When adding normal topic subscriptions, topic name[1] is created internally by appending node id. By default, there's a forward slash in default node id(NODE/192.168.1.1:4000). When using modified node id without a forward slash topic subscriptions can't be added due to topic naming validation failed.
**Reason :** When there's a forward slash it will separate topic name from forward slash resulting identifying topic name as  192.168.1.1:4000 in default case.
In modified node id scenario, if no forward slash separators it will identify whole name[2] as topic name. This will result in topic name validation failed due to "|" pipe characters.
With this PR pipe "|" has been replaced by underscore, and forward …
> [MB-1751] Fix unable to add normal topics with modified node id

- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
Changed table names that were too lengthy. Associated with https://github.com/wso2/carbon-business-messaging/pull/347
> Renaming of lengthy db table names

- modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
- modules/andes-core/management/common/src/main/java/org/wso2/andes/management/common/mbeans/QueueManagementInformation.java
Fixing: https://wso2.org/jira/browse/MB-1762
As it seems this issue happens because DAS only allows to monitor attributes which returns data types such as string, long, integer, boolean, double or Composite data objects that returns the above types. So any attribute which returns other types of data (ex. java.util.HashMap, string arrays) will not be listed.
Hence, exposed as Composite data
> Added MBean to expose queue message counts as composite data.

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageHandler.java
This fix tells fileWriter to append instead of replace.
> Fixing message status dump functionality 

- modules/andes-core/broker/src/main/java/org/wso2/andes/server/AMQChannel.java
This is to prevent multiple nodes generating same UUID for channel ID.
> Added a random UUID for channel ID.

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/MessageDeliveryTask.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/Slot.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeletionExecutor.java
Addresses the issue reported at https://wso2.org/jira/browse/MB-1831
The issues was caused when slots for a storage queue are being deleted after the queue is removed.
> [MB-1831] npe in slot deletion executor

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscriptionManager.java
Fixing: https://wso2.org/jira/browse/MB-1814
This fix may affect failover scenarios as well. When one member leaves the cluster coordinator node will go and clean up subscriptions made to that node. Only local subscriptions can be closed.
> [MB-1814] Fixed issue with filtering subscriptions to close when a member leaves in cluster.

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/DurableTopicSubscriber.java
Fixes the issue reported at https://wso2.org/jira/browse/MB-1830
Prevented the connection from being set to null upon connection close.
Related to https://github.com/wso2/andes/pull/718
> [MB-1830] Fixed issue in shared durable topic failover

- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/HazelcastCoordinationStrategy.java
Fix is trying to read nodeID in an exponentially back-off way.
Fixed: https://wso2.org/jira/browse/MB-1723
> [MB-1723] Fix Node ID is not set into Hazelcast map 

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/ConcurrentBatchEventHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/InboundEventHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/AckEventBatchHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/DtxDbWriter.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundEventManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/MessageWriter.java
- To make acknowledge handlers, transactional and non transactional message writers run in parallel (in disruptor) created the InboundEventHandler abstract class. All those handlers stem from this base class.
> Introduce InboundEventHandler abstract class

- modules/andes-core/broker/src/main/java/org/wso2/andes/server/txn/QpidDistributedTransaction.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/XAResource_0_9_1.java
- postCommit command for postTransactionActions are executed at
prepared state since after prepared we cannot rollback
- sibling map is update for both compared xaResources in
XAResource_0_9_1#isSameRM method
> Fix issues identified while write dtx.start join, resume test cases

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/MessagePreProcessor.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/dtx/DistributedTransaction.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/dtx/DtxBranch.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/dtx/DtxRegistry.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/AMQChannel.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/txn/QpidDistributedTransaction.java
- modules/andes-core/common/src/main/java/org/wso2/andes/transport/network/mina/MinaNetworkTransport.java
- When rollback is called return the messages that were acknowledged within the transaction
- Remove entries for none prepared distributed transactions from dtx registry when a session is closed.
> Fix rollback issue of not returning acked messages within transaction

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextInformationManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/StorageQueue.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/binding/BindingFactory.java
- For the durable topic, subscribers subscribe with the same subId but different topic, we do not replace binding rather keep the old and not allow to changed the binding. Therefore, removeBinding(existingMapping) call deleted in the BindingFactory#makeBinding. In non-durable topic subscription creation, code modified to add binding per node queue.
> NPE fixed when adding mix of subscribers multiple times

- modules/andes-core/client/src/main/java/org/wso2/andes/client/BasicMessageConsumer.java
Fixing [MB-1812.](https://wso2.org/jira/browse/MB-1812) Parent qpid code also has null checks before calling dispatcher. Fixing with same.
> [MB-1812][ESB + MB] Fixing nullpointer when calling through JMS transport

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextInformationManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscription.java
Last nondurable subscriber disconnect causes purge messages and deletes queue. In queue
delete, we again invoke close subscription and send a notification. It was repeated queue
delete again and end up with NPE. Therefore, invoking subscription close inside queue delete
was removed in the code. Also, when syncing subscription, cqengine query trying to
access a null object. Null check added to ROUTER_NAME and ROUTING_KEY.
> NPE in the mix subscriptions test case is fixed.

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/dtx/DtxRegistry.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/AMQChannel.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/DtxRecoverHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/ServerMethodDispatcherImpl_0_91.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/XAResource_0_9_1.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/XASession_9_1.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/handler/ClientMethodDispatcherImpl_0_91.java
- modules/andes-core/common/src/main/java/org/wso2/andes/dtx/XidImpl.java
- modules/orbit/andes-client/pom.xml
- modules/specs/amqp0-9-1.stripped.xml
The dtx.recover frame is used to query the broker node on distributed transaction in prepared state.
> Implement dtx.recover frame

- modules/andes-core/client/example/src/main/java/org/wso2/andes/example/publisher/MonitorPublisher.java
- modules/andes-core/client/example/src/main/java/org/wso2/andes/example/publisher/Publisher.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQConnectionFactory.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/XAResource_0_10.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/url/URLParser_0_10.java
There were inherited from Qpid's forked codebase.
> removed souts in andes client code.

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/AMQPLocalSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/NullSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/OutboundSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/SubscriberConnection.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/MQTTLocalSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/SubscriptionManagementInformationMBean.java
Non durable topic subscriber connection closed through subscription list page. The subscriber connection closed without issue. But topic couldn't delete in the topic list page due to registry resource not getting cleared. The issue was user subject not passed to the authorization when closing the connection. This was fixed by changing the close connection and delete registry entry as two different calls. 
Public JIRA - https://wso2.org/jira/browse/MB-1815
> MB-1815 issue fixed.

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlledQueueMessageDeliveryImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageStatus.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/BasicRejectMethodHandler.java
Scenario: When there is no subscriber with a matching selector if it is a queue message we place in on DLC. 
BUFFERED >> SCHEDULED_TO_SEND >> DLC (invalid transition)
With the fix
BUFFERED >> NO_MATCHING_CONSUMER >> DLC
> [MB-1703] added new message status NO_MATCHING_CONSUMER

- modules/andes-core/broker/src/main/java/org/wso2/andes/task/TaskProcessor.java
There are instances that taskholder becomes null. At such a situation we set "null" to task id.
> [MB-1842] Added null for task id when taskholder becomes null.

- modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/MessageDeliveryTask.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/Slot.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotCoordinator.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeletingTask.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotDeletionExecutor.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
WSO2 MB reads slots, deliver messages and remove them from memory if all messages are ACKED of that slot. This deletion happens with a cluster-wide agreement (safe zone value calculation).
We have seen issues slots are getting accumulated in long running due to various reasons.
1. A few messages are not always ACKED. So slot remains
2. Slot deletion task gets inactive? 
3. Safe zone value calculation is jumbled
nodes are not time synced
heat beat stops
So it is better to know if slots are getting accumulated ahead before situation get worse. Thus need a WARN level log that prints every now and again.
Also need to make several slot deleting tasks to execute slot delete tasks in parallel (using thrift connection pool) because slot read happens in parallel (slot delivery worker threads > 1) …
> [MB-1865] Added modifications to execute slot deleting tasks in parallel.

- modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotMessageCounter.java
Slots are simulated in standalone mode. Thus they need to be removed in standalone mode as well.
> Fix slot delete in standalone mode.

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DisruptorBasedFlusher.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundEventManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/waitStrategy/SleepingBlockingWaitStrategy.java
The SleepingBlockingWaitStrategy consumes less CPU than BlockingWaitStrategy since it does not spin while waiting for dependent processors
> Change Disruptor wait strategy

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/QpidAndesBridge.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesMessagePart.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DtxStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/compression/LZ4CompressionHelper.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/ContentChunkHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/dtx/DtxRegistry.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/mqtt/utils/MQTTUtils.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingDtxStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSDtxStoreImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java
- modules/andes-core/broker/src/test/java/org/wso2/andes/kernel/disruptor/inbound/ContentChunkHandlerTest.java
- modules/andes-core/common/src/main/java/org/wso2/andes/dtx/XidImpl.java
- DtxRegistry will populate an internal hash set with stored xids in the database that are not in memory. Call to #getBranch will check the hash set before querying the database for the branch. To improve the performance of Dtx.start by avoiding an extra DB call for a nonexisting branch.
- Remove dataLength property from AndesMessagePart since the value can be derived using the data.
> Add a hash set to keep track of stored Xids in DtxRegistry

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/NullSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/SubscriptionManagementInformationMBean.java
Null subscription assigned if the subscriber connection is not a local. But when rendering nondurable subscriptions, we are fetching all subscriptions. Therefore, the condition added to check whether the subscription is local or not and based on that protocol queue name will retrieve. Also, NullSubscription class modified to return UnsupportedOperationException.
NullPointerException didn't occur following the given steps.
Public JIRA - https://wso2.org/jira/browse/MB-1892
> MB-1892 issue fixed.

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/QpidAndesBridge.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesConstants.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/BasicConsumeMethodHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/ExchangeBoundHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/QueueBindHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/QueueDeclareHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/QueueDeleteHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/QueuePurgeHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/QueueUnbindHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/queue/AMQQueueFactory.java
- modules/andes-core/common/src/main/java/org/wso2/andes/framing/AMQShortString.java
- modules/andes-core/common/src/main/java/org/wso2/andes/framing/abstraction/MessagePublishInfoImpl.java
- modules/andes-core/common/src/main/java/org/wso2/andes/framing/amqp_0_9/MethodConverter_0_9.java
- modules/andes-core/common/src/main/java/org/wso2/andes/framing/amqp_0_91/MethodConverter_0_91.java
- modules/andes-core/common/src/main/java/org/wso2/andes/framing/amqp_8_0/MethodConverter_8_0.java
Addresses the issue reported at https://wso2.org/jira/browse/MB-1902
Queue names are converted to the lower case before processing any further, so that no 2 queues from different cases are accepted into the core.
Queue names are turned to lower case when the admin services are called in https://github.com/wso2/carbon-business-messaging/pull/419
Test cases are modified in https://github.com/wso2/product-mb/pull/468
> Made queue names case insensitive

- modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/QueueBindHandler.java
When adding durable topic subscriber for the first time, binding added to QPID registry. Once restart the server, these details read from the db and feed to QPID. But we do not persist FieldTable arguments to the database. Therefore, adding a durable topic subscriber to the restart server will adding binding each time it connects. These arguments are not used in any places and only use to do equal check at adding a subscription. All the other places passed null as the value. To avoid add binding again, I have passed null as argument.
> Bind adding to already bound durable topic issue fixed.

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
Fixes the issue reported at https://wso2.org/jira/browse/MB-1906
The NullPointerException was cased by the storage queue not being set to the slot when read from the database. The resolution was to set it manually once the slot is read when a member leaves.
> Fixed NullPointerException in slot deletion

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundEventManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/tools/utils/MessageTracer.java
Added tracing for transactions when messages are enqueued and when a transactions id commited/rollbacked/closed.
The issue is tracked at https://wso2.org/jira/browse/MB-1907
> Message tracing for local transactions

- modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java
Fixes the issue reported at https://wso2.org/jira/browse/MB-1908
An empty slot was created when node that has no publishers connected gets killed, restarted and gets connected to consumers. 
This was caused by the fact that the last published message id in the was updated according to the number of messages for a given queue(which in this case, is zero). The slots were created according to the last published message id for each queue, hence ended up having a slot with the end message id as zero. This resulted in an invalid slot which was never removed even though there were no messages in it.
The fix was to not update the last published message id, if there are no messages for a queue.
> [MB-1908] Fixed issue with empty slot

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DeliveryEventHandler.java
If durable queue/topic subscriber got an error while sending the message, then it is routed to the DLC.
But in the current implementation, if any error occurred, the message got deleted instead of routing to DLC.
The reason is we are setting internalErrorOccurred to true. This PR modified routeMessageToDLC method
by removing the above-mentioned parameter. Now messages will be routed to DCL in a case of error
situation while sending. Only nondurable topic subscriber messages will be discarded.
> MB-1901 issue fixed.

- modules/andes-core/client/src/main/java/org/wso2/andes/client/XASession_9_1.java
- modules/andes-core/client/src/main/java/org/wso2/andes/jms/FailoverPolicy.java
- modules/andes-core/client/src/main/java/org/wso2/andes/jms/failover/FailoverMethod.java
- modules/andes-core/client/src/main/java/org/wso2/andes/jms/failover/FailoverOneTime.java
- modules/andes-core/client/src/main/java/org/wso2/andes/jms/failover/FailoverRoundRobinServers.java
Suggestions for a different failover policy name is welcomed. :smiley: Currently we use the name "onetime". Broker URL will look something like below.
```
connectionfactory.QueueConnectionFactory = amqp://admin:admin@clientID/carbon?failover='onetime'&cyclecount='2'&brokerlist='tcp://localhost:5673?retries='5'&connectdelay='50';tcp://localhost:5674?retries='5'&connectdelay='50';tcp://localhost:5675?retries='5'&connectdelay='50''
```
> XA transactions fail-over testing fixes

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotMessageCounter.java
Fixes the issue of the safe zone not getting updated in a fail-over scenario reported at https://wso2.org/jira/browse/MB-1909
The issue was due to the fact that 'slotSubmitLoopSkipCount' in SlotMessageCounter(which is compared with SLOT_SUBMIT_LOOP_SKIP_COUNT_THRESHOLD to update the safezone) is not being reset when a connection exception occurs when the coordinator goes down. 
Removed 'slotSubmitLoopSkipCount' itself since the operation to update the safe zone already happens as a scheduled task.
> [MB-1909] fixed issue in safe zone update

- modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQConnection.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQConnectionDelegate_8_0.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQConnectionFactory.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/protocol/AMQProtocolHandler.java
1. Enforce synchronized behaviour when writing frames to the channel from andes client side.
2. Allow custom connection listener through AMQConnectionFactory so that an external failover logic can take precedence over the in-built andes failover logic. Refer class at [1] for the ConnectionListener interface.
3. Use a new AMQProtocolHandler object when retrying to connect to the MB cluster. This will avoid any blockage from stale connection states from previous AMQProtocolHandler objects. 
4. Ensure closure of stale mina sockets when the connection times out or if an exception occurs during retry attempts.
> MB-1905 - Failover issues with 800 subscribers

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/ExpiredMessageHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/PeriodicExpiryMessageDeletionTask.java
Message deleted by expiration task doesn't provide proper information to the outside. Therefore, WARN log added indicating that message will delete.
Example:
`[2017-03-14 12:20:52,210]  WARN {MessageExpirationTask} -  Message is expired. Therefore, it will be deleted. : id= 51510740731559946`
> MB-1889 issue fixed.

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/dtx/DistributedTransaction.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/RDBMSCoordinationStrategy.java
This to avoid an edge case issue where the coordinator's heart beat entry update get delayed for a long period due to a performance issue in either in the network or the DBMS. The added expiration task will remove the coordinator state from the current node state if the update did not happened before the heart beat max age to avoid inconsistency between DB and memory states.
> Add COORDINATOR state expiration task

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscriptionManager.java
The issue is tracked at https://wso2.org/jira/browse/MB-1912
The issue was caused by the fact that subscriptions are not bound to storage queues if the subscription is a remote one. Hence when a node with non-durable subscriptions get killed, newly appointed coordiantor would delete the bound queue upon removal of the first subscription itself. The resolution was get the actuall subscription count across the cluster from the subscription registry prior to deleting the queue
> [MB-1912] issue in non-durable subscription failover

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DeliverableAndesMetadata.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/ExpiredMessageHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageStatus.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/PeriodicExpiryMessageDeletionTask.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/PreDeliveryExpiryMessageDeletionTask.java
Introduced new message status "PREPARED_TO_DELETE"
PREPARED_TO_DELETE.next = EnumSet.of(DELETED, SLOT_REMOVED);
PREPARED_TO_DELETE.previous = EnumSet.of(EXPIRED, DLC_MESSAGE, PURGED);
This is to solve asynchronous message deletion and asynchronous slot deletion performed.
> [MB-1893] Fixed state transition issue while deleting expired  messages

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/slot/SlotManagerClusterMode.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/SlotAgent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/rdbms/DatabaseSlotAgent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingAndesContextStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
This addresses the issue (reported at https://wso2.org/jira/browse/MB-1916) of some slots being remained in the database in a 2 node cluster fail-over scenario where an overlapped slot was destined to the killed node. The fix was to either delete such overlapped slots(if empty) or to re-assing (if not empty) when a member removed event is received by the coordinator.
> Re-assigend overlapped slot when member leaves

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/Andes.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingMessageStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java
- modules/andes-core/management/common/src/main/java/org/wso2/andes/management/common/mbeans/QueueManagementInformation.java
provides 2 new Admin services with regard to DLC operations within the server.
getMessageMetadataInDeadLetterChannel
Returns a paginated list of message metadata destined for the targetQueue but currently living in the
Dead Letter Channel.
@param targetQueue Name of the destination queue
@param startMessageId Start point of the queue message id to start reading
@param pageLimit Maximum number of messages required in a single response
rerouteAllMessagesFromDeadLetterChannelForQueue
Move messages destined for the input sourceQueue into a different targetQueue.
If the sourceQueue is DLCQueue, all messages in the DLC will be restored to the targetQueue.
@param sourceQueue Name of the source queue
@param targetQueue Name of the target queue.
@param internalBatchSize even with this method, the …
> MB1737 - Add new admin services to retrieve messages without content to increase performance.

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextInformationManager.java
In a cluster setup thought a queue is deleted, it is still listed in the UI even after the 'Queue sync [delete]' logged.
This is due to adding queue mappings twice inside AndesContextInformationManager::syncCreateBinding(). To fix this, removed one addMapping() call.
> [MB-1914] Fix : Adding queue mappings twice in sync nodes

- modules/andes-core/client/src/main/java/org/wso2/andes/client/BasicMessageConsumer.java
When rolling back messages not yet seen by the application, iteration of the DelayedQueue will cause jumbling of message order. Therefore used a while -> take/pull loop.
*Further ordering issues still occur if the subscriber is consuming messages without any delay. These will be fixed later.
> MB-1895 - Fix #1 - message order during transaction rollback. 

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/RDBMSCoordinationStrategy.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/ClusterNotificationListenerManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/HazelcastClusterNotificationListenerImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/rdbms/RDBMSClusterNotificationListenerImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingAndesContextStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
This is to avoid cluster information (heartbeat data, cluster notifications, membership notifications) getting removed after initializing the coordination strategy. Only information destined to current node will be removed.
> Avoid clearing clustering information at startup

- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/hazelcast/HazelcastBasedNotificationAgentImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/coordination/rdbms/RDBMSBasedNotificationAgentImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
RDBMS coordination read notifications from MB_CLUSTER_EVENT and MB_MEMBERSHIP tables.
After selecting notifications, those are deleted by the destined node. This would
lead delete unread notifications in a high concurrent scenario. The fix is select
notifications with event id and then delete notifications by event id.
Additionally, DEBUG logs modified with more details in RDBMSBasedNotificationAgentImpl
and HazelcastBasedNotificationAgentImpl.
Public JIRAs - https://wso2.org/jira/browse/MB-1839, https://wso2.org/jira/browse/MB-1881
> Fix cluster notification missing in the RDMBS coordination

- modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
This PR contains the fix for the NPE thrown when restoring messages having empty content from the DLC queue.
Fix : https://wso2.org/jira/browse/MB-1922
> [MB-1922] Fix : NPE when restoring empty messages from DLC queue

- modules/andes-core/broker/src/main/java/org/wso2/andes/server/cluster/RDBMSCoordinationStrategy.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQConnectionFactory.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/XAConnectionImpl.java
This to avoid stale connections when a commit or rollback get delayed for a long time.
https://wso2.org/jira/projects/MB/issues/MB-1921
> [MB-1921] Add a scheduled close task to XAConnectionImpl

- modules/orbit/andes-client/pom.xml
- pom.xml
This change fix the issue https://github.com/wso2/product-ei/issues/453 in product-ei. It happens due to unnecessary export of org.apache.commons.lang.* package from andes-client. With the fix, it is added as import package and removed from export packages.
> Fix OSGI issue in andes-client with EI

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DeliverableAndesMetadata.java
Addresses the issue reported at https://wso2.org/jira/browse/MB-1920
A message which has 2 delivery statuses as RECOVERED and ACKED from 2 different channel will get deleted upon the ack.
> [MB-1920] fixed issue of messages not being deleted in fail-over

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/dtx/DtxBranch.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/dtx/DtxRegistry.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSDtxStoreImpl.java
When multiple sessionis initiated with multiple connections work on
a single distributed transaction branch the ArrayList used to keep
enqueued records are accessed parallely. To avoid this behaviur the
enqueue method is synchronized.
https://wso2.org/jira/browse/MB-1910
> Fix MB-1910

- modules/andes-core/client/src/main/java/org/wso2/andes/client/BasicMessageConsumer.java
Rejection was send upon closing the consumer hence separated the recovery in Autoack mode.
> Fix MB-1929

- modules/andes-core/common/src/main/java/org/wso2/andes/util/Strings.java
This PR fixes https://github.com/wso2/product-ei/issues/693 which is caused by the charbuf theradlocal variable of org.wso2.andes.util.Strings class
> Fix #693 of EI, the memory leak caused by charbuf threadlocal variable

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DtxStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/ContentChunkHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/DtxDbWriter.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundEventContainer.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/MessagePreProcessor.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/dtx/DtxBranch.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/dtx/DtxRegistry.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingDtxStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSDtxStoreImpl.java
Issue: wso2/product-ei#737
During prepare step, the messages to be dequeued are deleted from MB_METADATA table and moved into MB_DTX_DEQUEUE_RECORD and also acknowledged. The messages to be enqueued are inserted to MB_DTX_ENQUEUE_RECORD.
During the commit step, the in-memory enqueue list of the dtx branch is inserted to the MB_METADATA table. And the dequeue records in the MB_DTX_DEQUEUE_RECORD are removed.
During a one phase commit scenario, prepare step is not executed and commit step is directly executed. In that case, in-memory enqueue list will get inserted to the MB_METADATA table just as before. But, the dequeue list will still remain in MB_METADATA unacknowledged. So to fix this we need to directly acknowledge and remove dequeue list from MB_METADATA table if it is a one-phase …
> Fix wso2/product-ei#737

- modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
We now have two options for "deployment/mode". They are,
- **standalone** - This is the simplest mode a broker can be started. The node will assume that message store is not shared with another node. Therefore it will not try to coordinate with other nodes (possibly non-existent) to provide HA. This is the default configuration used.
- **clustered** - Broker node will run in HA mode (active/passive).
> Change deployment configurations

- modules/orbit/andes-client/pom.xml
- pom.xml
Upgrade Carbon-Kernel and related dependencies to latest
Following components are updated,
- Carbon-Kernel    5.2.0
- Carbon-Secvault 5.0.8
- Carbon-Metrics  2.3.2
> Upgrade Carbon-Kernel to 5.2.0

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DeliveryEventData.java
References to Objects in Disruptor are not cleared properly after using. This fix clears the references after usage within Disruptor
> https://github.com/wso2/product-ei/issues/1113
> Clear references for objects within Disruptor after usage. 
> Last event handler of the Disruptor clears all the object reference from the Disruptor event container objects. In outbound and inbound disruptor we have missed clearing some newly introduced objects, With this fix, we are clearing those objects as well from the Disruptor buffer with the last event handler.
> User publishes and consumes message from the broker. Once the messages get consumed references to delivered messages and already closed channels should be GC'ed
> Clear references for objects within Disruptor after usage. 
> No documentation …
> Fix for ei#1113

- modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQBrokerDetails.java
- modules/andes-core/common/src/main/java/org/wso2/andes/url/URLHelper.java
If the connection url specified in the jndi context fails to parse, the andes client includes the full url into the exception message. Since this url can contain passwords, this commit avoids adding the such sensitive data into the exception object.
Public Jira : https://wso2.org/jira/browse/APIMANAGER-5915
> Avoid connection credentials in console logs

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DeliveryEventCleanupHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DeliveryEventData.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DeliveryEventHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DisruptorBasedFlusher.java
Resolves wso2/product-ei#1113
Clears references for objects within Disruptor after usage.
Last event handler of the Disruptor clears all the object reference from the Disruptor event container objects. In the outbound disruptor, we have missed clearing some newly introduced objects, With this fix, we have added a new handler for clearing those objects as well from the Disruptor buffer.
N/A, this is a bug fix to prevent the server from going OOM.
Clear references for objects within Disruptor after usage.
N/A, this is a bug fix
N/A, this is a bug fix
N/A, this is a bug fix
N/A, this is a bug fix
N/A, Need to manually test a heap dump to identify this. Since this is a probable OOM scenario.
- Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guideli …
> Fix NullPointerException during messaging

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/AMQPUtils.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesAckEvent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesEncodingUtil.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesMessageMetadata.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DeliverableAndesMetadata.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessagingEngine.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/LZ4ContentCompressionStrategy.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/MessagePreProcessor.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/dtx/AndesPreparedMessageMetadata.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/message/AMQMessage.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/message/MessageMetaData.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/message/MessageMetaData_0_10.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/queue/DLCQueueUtils.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/store/MessageMetaDataType.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingMessageStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSDtxStoreImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSMessageStoreImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/tools/messagestore/commands/Show.java
- modules/andes-core/broker/src/test/java/org/wso2/andes/server/exchange/AbstractHeadersExchangeTestBase.java
> Implement a new Andes message metadata implementation to make broker core independant from the existing Qpid code.
> Created a new AndesMessageMetadata implementation that doesn't depend on Qpid
> Implement Qpid independent message metadata format for the broker
> This metadata implementation is not compatible with older metadata format. Hence DB data migration is required when moving from 3.xx versions to 4.xx
> Add Qpid independant Andes metadata implementation

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/StorageQueue.java
> We deliver messages for a given queue based on a cursor that moves forward while delegating every N messages to all active subscribers. However, if the last subscriber leaves abruptly, the next subscription will not receive the messages previously allocated. Thus, resetting the cursor.
> Reset message cursor when last subscriber leaves

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/AMQPLocalSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/delivery/DeliveryEventHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/subscription/SubscriptionImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/MBThriftServer.java
- modules/andes-core/common/src/main/java/org/wso2/andes/AMQSubscriptionClosedException.java
To fix https://github.com/wso2/product-ei/issues/1619 and https://github.com/wso2/product-ei/issues/1613. 
Fixes the NPE that occurs when a subscription connection is abruptly removed. The issue was caused by a message duplication. Messages that are failed during delivery were requeued where all the messages that are bound to the subscription are also requeued from another path. As the resolution, avoided requeueing messages when the delivery is failed due to the subscriber being not available.
This fix provided by @sdkottegoda .
> Fix NPE when subscriber closed and Thrift server thread hang and Thrift server hangs in socket read

- modules/andes-core/broker/src/main/java/org/wso2/andes/server/AMQChannel.java
2nd node unable to create the durable subscription with the same subscription id after the first node disconnect.
Resolves https://github.com/wso2/product-ei/issues/1644
2nd node should able to create the new durable subscription with the same subscription id after the first node disconnect.
Creating a  durable subscription on the second node that was made with the same subscription id after disconnecting from the other node fail in a 2 node MB cluster. Ref: wso2/product-ei#1644
> Fix EI-1644

- modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQConnection.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQConnectionFactory.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/state/AMQStateManager.java
Remove redundant error logging from the client code on connection failures
> Remove redundant error logs from Andes client code

- modules/andes-core/client/src/main/java/org/wso2/andes/client/protocol/AMQProtocolHandler.java
Remove redundant error logging done by Andes client. Error is thrown and logged at the same place.
> Remove redundant error logging from Andes client

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/QpidAndesBridge.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/FlowControlledQueueMessageDeliveryImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/NoLossBurstTopicMessageDeliveryImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/SlowestSubscriberTopicMessageDeliveryImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundSubscriptionEvent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscriptionManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/OutBoundMessageTracker.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/SubscriberConnection.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/AMQChannel.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/BasicConsumeMethodHandler.java
- modules/andes-core/broker/src/test/java/org/wso2/andes/server/util/InternalBrokerBaseCase.java
> Fix wso2/product-ei/issues/1845
> Sends consume-ok before start sending messages to subscriber
> Use a runnable object to send comsume-ok frame in AndesSubscriptionManager Class. 
Use a new setReadyToDeliver method to hold outbound from start sending messages to consumers.
After consume-ok frame sent by the thread. We are releasing outbound using setReadyToDeliver(true)
> JDK 8, Ubuntu 16.04
> Fix wso2/product-ei/issues/1845

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundSubscriptionEvent.java
> Fix to avoid NPE when try to run post subscription action.
> NPE throws from Andes kernel when tries to subscribe to a MQTT topic. This is to fix that issue
> Initialize postOpenSubscriptionAction runnable in InboundSubscriptionEvent class inside the overloaded constructor which doesn't allow to set it externally. 
> N/A, Bug fix
> Fix to avoid NPE when try to run post subscription action
> N/A, Bug fix
> N/A, Bug fix
> N/A, Bug fix
> N/A, Bug fix
> N/A, Bug fix
> N/A, Bug fix
> https://github.com/wso2/andes/pull/958
> …
> Fix to avoid NPE when try to run post subscription action

- modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/MessageStatus.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/PreDeliveryExpiryMessageDeletionTask.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
New Improvement : Move expired messages to DLC
To enable edit [MB_HOME]/repository/conf/broker.xml file and define below parameter.
```
<performanceTuning> ...
<messageExpiration> ...
<moveExpiredMessagesToDLC> true </moveExpiredMessagesToDLC>
```
Fixes : wso2/product-ei#1914
> Read a global setting from broker.xml to control the behavior. 
> Expired messages should not be deleted. They should be move into Dead Letter Channel instead.  
> Feature : expired messages are not removed, but routed to DLC. You can restore them back with expiry time reset. 
> Refer above
> Move expired messages to DLC and see.
> N/A
N/A
- Unit tests 
> Code coverage information
- Integration tests
> Details about the test cases and coverage
- Followed secure coding standards in …
> Move expired messages to DLC

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AMQPMetaDataHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesMessageMetadata.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
> Fixes : wso2/product-ei#1914
This improvement is to modify message expire time when moving message
Back to the original queue
Reroute to a different queue
This will modify expire time of the original message to 0 to indicate no expiration. 
Calculation is done by
New expire time = Current time + (original expire time - original arrival time)
If you reroute or restore DLC messages, if expire time was specified in original message, it is ignored and message will never expire when rerouting/restoring. 
> Update: https://docs.wso2.com/display/MB320/Using+the+Dead+Letter+Channel (relevant page on next version)
N/A
N/A - small feature
N/A
- Will be added when integration framework support JMS Tests
- …
> Modify expirery+arrival times upon restore from DLC

- modules/andes-core/client/src/main/java/org/wso2/andes/client/BasicMessageConsumer.java
- modules/andes-core/client/src/main/java/org/wso2/andes/jms/ConnectionURL.java
- modules/andes-core/client/src/test/java/org/wso2/andes/unit/client/connectionurl/ConnectionURLTest.java
Fix https://github.com/wso2/product-ei/issues/1952
> Currently redelivery delay can be set as System Property "AndesRedeliveryDelay". With this fix, we are enabling for the delay to be set as a connection string in addition to system property.
> Making redelivery delay a connection parameter.
>Adding a connection option named **redeliverydelay** for the connection url.
Eg:-
connectionfactory.QueueConnectionFactory = amqp://admin:admin@clientID/carbon?brokerlist='tcp://localhost:5673'
connectionfactory.QueueConnectionFactory1 = amqp://admin:admin@clientID/carbon?redeliverydelay='15000'&brokerlist='tcp://localhost:5673'
> With this fix, users can configure redelivery delay as a connection option.
> https://docs.wso2.com/display/MB320/Setting+the+Connection+URL
- Unit tests > Provided
- …
> Make redelivery delay a configurable connection option

- modules/andes-core/broker/src/main/java/org/wso2/andes/server/protocol/AMQProtocolEngine.java
Fix: https://github.com/wso2/product-ei/issues/2154
When MB Client throws a javax.jms.IllegalStateException ESB continuously failover to same node. Fix is to prevent throwing  javax.jms.IllegalStateException and notify closing the connection. 
N/A 
JDK 8
> Fix EI-2154

- modules/andes-core/broker/src/main/java/org/wso2/andes/server/information/management/QueueManagementInformationMBean.java
Fixes the issue of message content being displayed as '-1' when an empty message is published and browsed through the UI.
Resolves https://github.com/wso2/product-ei/issues/2321
Changed the functionality so that the message "This operation is not supported" is displayed when trying to view the message content.
> Fix product-ei/issues/2321

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscriptionManager.java
Resolves https://github.com/wso2/product-ei/issues/2320
Fixes the issue of active durable subscriptions not being listed once searched by the subscription identifier, by having the filtration done using the storage queue associated with the subscription as well as the subscription id.
> Fix Issue in Active Durable Subscription Search

- modules/andes-core/broker/src/main/java/org/wso2/andes/configuration/enums/AndesConfiguration.java
Enables the functionality of re-routing all messages that belong to a
queue by default as opposed to a configuration in broker.xml.
Resolves: https://github.com/wso2/product-ei/issues/2322
https://github.com/wso2/carbon-business-messaging/pull/641
> Improve Reroute All From DLC

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/AMQPUtils.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/QpidAndesBridge.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/binding/BindingFactory.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/queue/AMQQueue.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/queue/SimpleAMQQueue.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/virtualhost/VirtualHostConfigSynchronizer.java
- modules/andes-core/broker/src/test/java/org/wso2/andes/server/queue/MockAMQQueue.java
MB should not send binding delete requests triggered from queue delete cluster sync requests. This PR marks the binding removal done from cluster sync tasks as non local.
This fixes the issue reported in https://github.com/wso2/product-ei/issues/2352
> Fix for wso2/product-ei#2352

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscriptionManager.java
Fixes thread death when unsubscribing a subscription from UI. 
Resolves: https://github.com/wso2/product-ei/issues/2347
The underlying cause was a dead lock in the disruptor that occured when the DB recovery task runs. The DB recovery event(a disruptor event) detects conflicts of the connected node of local subscriptions and susbscriptions stored in the databse. Once a conflict is detected it disonnects the local subscription resulting in an event being published to the disruptor. This causes all disruptor handlers to hang thus MB
being barely usable. The resolution for this is decouple the local subscription being deleted from the detection of the conflict.
> Fix EI-2347

- modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQConnection.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/pool/NamedThreadFactoryBuilder.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/pool/ReferenceCountingClientExecutorService.java
> Fix issue https://github.com/wso2/product-ei/issues/2432
> Fixing an issue regarding EI re-connect to MB after DB failure at MB. 
> A separate executor service is introduced to notify the connection exception listeners. We cannot use the JOB pool threads for notifying the exception listeners since it will block the frame processing which is critical for activities like connection handshakes.
> EI should automatically reconnect once MB recovers from failure 
> N/A
> N/A
> N/A
> N/A
- Unit tests 
>  Not added 
- Integration tests
> Not Added
- Followed secure coding standards in …
> Fix [EI-2432] EI cannot re-connect to MB after DB failure

- modules/andes-core/broker/src/main/java/org/wso2/andes/server/binding/BindingFactory.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/handler/QueueBindHandler.java
Permission for queue consume is granted during the binding
authorization. The issue was caused due to the fact that the permission
check for binding was done after adding the binding. This existence of
the incorrect binding causes the next consume call to be directly
checked for autherization skipping necessary permission granting
in binding creation.
Resolves: wso2/product-ei#2631
A user is granted permission to consume from a queue upon being authorized for the binding. Authorization for binding only happens for a new binding. The second user with the same subscription id is not granted permission to consume from the queue since binding authorization is skipped.
Resolves: wso2/product-ei#2603
>  Fix issues in authorization

- modules/andes-core/broker/src/main/java/org/wso2/andes/thrift/MBThriftClient.java
> To fix the "java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'xxxx' for key 'PRIMARY'” database error, caused when inserting Slot Message IDs to MB_SLOT_MESSAGE_ID table.
> To stop retrying once the operation becomes successful.
> Fix [wso2/andes#1013](https://github.com/wso2/andes/issues/1013)
> Fix duplicate primary keys issue

- modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQConnection.java
- modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQSession.java
Create a single thread pool for message rejection task for
Andes client
Fixes : https://github.com/wso2/product-ei/issues/3897
> Improve thread usage for message rejection

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/MaximumNumOfDeliveryRule.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AMQPMetaDataHandler.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesConstants.java
For customers sometimes it is an important feature to know the delivery count of the message.
Following are instances messages are redelivered from the broker.
if client rollbacked the session (on a transacted session)
recover the session before acknowledging
application did not acknowledge, client will send NAC upon ack time out.
JMS 2.0 brings up a solution by introducing standard Int type header called JMSXDeliveryCount. It can be used by JMS 1.1 applications as well because, both APIs have the ability to read the JMS header properties.
In WSO2 EI this property can be read as a transport level header in an incoming message from `Axis2 JMS Transport` or `Inbound JMS Transport`.
Fixes: https://github.com/wso2/product-ei/issues/4636
Port: https://github.com/wso2-support/andes/pull/197
> Add JMSXDeliveryCount Header to WSO2 MB

- modules/andes-core/broker/src/main/java/org/wso2/andes/amqp/QpidAndesBridge.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/DeliverableAndesMetadata.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/disruptor/inbound/InboundMessageRejectEvent.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/subscription/AndesSubscription.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/server/AMQChannel.java
[Fix EI-4795] MB XDeliveryCount header does not reflect correct values
Fixes: https://github.com/wso2/product-ei/issues/4795
Fix the race condition on requeing messages 
N/A
N/A
N/A
N/A
Will add integration test 
yes
> Provide high-level details about the samples related to this feature
> [Fix EI-4795] MB XDeliveryCount header does not reflect correct values

- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextInformationManager.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesContextStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/kernel/AndesKernelBoot.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/FailureObservingAndesContextStore.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSAndesContextStoreImpl.java
- modules/andes-core/broker/src/main/java/org/wso2/andes/store/rdbms/RDBMSConstants.java
Fix wso2/product-ei#4336
Fix wso2/product-ei#4337
Unable to create a durable topic subscription with the same name when the servers crash
This was fixed by removing all durable and non-durable subscriptions in cluster initialization.
NullPointerException in MB clusters when there are network delays
This was fixed by establishing the same old binding when a network delay occurs.
> Fix message broker unstable with subscription issue

- modules/andes-core/client/src/main/java/org/wso2/andes/jndi/Utils.java
Fix for https://github.com/wso2/product-apim/issues/12718
Due to the fix done in from https://github.com/wso2/andes/pull/1041 , exception is thrown when the connection URL is provided as `amqp://admin:$secret{admin_password}@clientid/carbon?brokerlist='tcp://${carbon.local.ip}:${jms.port}'` . 
Fix is done to handle these types of urls
> Fix secure vault enabled password issue in jms url

- modules/andes-core/client/src/main/java/org/wso2/andes/client/AMQConnectionDelegate_8_0.java
- modules/andes-core/client/src/main/java/org/wso2/andes/jms/BrokerDetails.java
- modules/andes-core/common/src/main/java/org/wso2/andes/transport/network/mina/MinaNetworkTransport.java
In a distributed WSO2 API Manager setup, throttling functionality was not working correctly when one or more traffic manager nodes were unavailable. Specifically, when one traffic manager node could not establish a connection while another was still active, event duplication led to threads becoming stuck, causing throttling failures.
- Resolves https://github.com/wso2/api-manager/issues/3125
Use the broker connection timeout property to introduce a waiting timeout for the broker pooled connection establishment
The process of establishing a broker connection will continue trying until the specified timeout is reached. If a timeout is defined in the broker's URL properties, that value will be used. Otherwise, the connection attempt will default to a 120-second timeout if no specific connect …
> [APIM][4.4.0] Configure Broker Connect Timeout to avoid Indefinite Waiting

- modules/andes-core/client/src/main/java/org/wso2/andes/client/protocol/AMQProtocolHandler.java
Log the fail-over thread name and the thread ID
Related to - https://github.com/wso2/api-manager/issues/3323
> Log the fail-over thread name and ID
